#region Copyright info
//-----------------------------------------------------------------------
// <copyright file="EntityN" company="Company">
//     Copyright (c) 2020. Company. All Rights Reserved.
//     Copyright (c) 2020. Company. Todos los derechos reservados.
//
//     .en This code has been generated by a tool, please don't modify this file or  
//     you will lost all your modifications in the next regeneration.
//      The original t4 template to get this file is " ApplicationEntityDtoCT.tt" with "public class ApplicationEntityDtoCT : Template"
// 
//     .es Este código ha sido generado por una herramienta, por favor no modifique este fichero
//     o perdera las modificaciones al regenerar este fichero.
//      La plantilla con que se ha generado este fichero es "ApplicationEntityDtoCT.tt" con "public class ApplicationEntityDtoCT : Template"
//
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace Needel.Common.Application.Dtos
{

    #region SharedKernel usings
    #endregion

    #region usings
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Inflexion2.Application;//.DataTransfer.Base;

    using Needel.Common.Domain.Data;

    using System.Collections.ObjectModel;
    #endregion

    /// <summary>
    /// Clase que representa a la entidad <see cref="EntityNDto"/>.
    /// </summary>
    /// <remarks>
    /// Crea un objeto <see cref="EntityNDto"/>.
    /// </remarks>
    // no tiene subclases
    // no tiene superclases
    [DataContract]
    public  class EntityNDto : BaseEntityDataTransferObject<Int32> 
    {
        #region CONSTRUCTORS
        
        /// <summary>
        /// Inicializa una nueva instancia de la clase <see cref="EntityNDto"/>.
        /// </summary>
        /// <remarks>
        /// Constructor de la clase <see cref="EntityNDto"/>.
        /// </remarks>
        public EntityNDto()
        {
            this.MZs = new System.Collections.Generic.List<MNZDto>();
        } // EntityNDto Constructor

        #endregion

        #region PROPERTIES

        /// <summary>
        /// Variable privada que identifica Name.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public string Name {get; set;}

        /// <summary>
        /// Campo privado para almacenar la colección de  MZs.
        /// </summary>
        /// <remarks>
        /// Nos permite establecer y obtener MZs.
        /// Propiedad proveniente del rol target de una relación.
        /// </remarks>
        [DataMember]
        public System.Collections.Generic.List<MNZDto> MZs {get; set;}/*from targets*/
        #endregion

        #region Actual IClonable implementation

        /// <summary>
        /// Actual IClonable implementation to help the IEditableObject Implementation 
        /// </summary>
        /// <returns></returns>
        public override object Clone()
        {
            var obj = new EntityNDto();
            obj.Id = this.Id;
            obj.Name = this.Name;

            //Parents from sources

            //Children from targets
            if (this.MZs != null && this.MZs.Count > 0)
            {
                obj.MZs = new System.Collections.Generic.List<MNZDto>();
                foreach (var item in this.MZs)
                {
                    obj.MZs.Add((MNZDto)item.Clone());
                }                
            }

            return obj;
        }
        #endregion

    } // end class EntityNDto
} //  Needel.Common.Application.Dtos

