#region Copyright info
//-----------------------------------------------------------------------
// <copyright file="Persona" company="Atento">
//     Copyright (c) 2016. Atento. All Rights Reserved.
//     Copyright (c) 2016. Atento. Todos los derechos reservados.
//
//     .en This code has been generated by a tool, please don't modify this file or  
//     you will lost all your modifications in the next regeneration.
//      The original t4 template to get this file is " InfraestructureEntityRepositoryCT.tt" with "public class InfraestructureEntityRepositoryCT : Template"
// 
//     .es Este código ha sido generado por una herramienta, por favor no modifique este fichero
//     o perdera las modificaciones al regenerar este fichero.
//      La plantilla con que se ha generado este fichero es "InfraestructureEntityRepositoryCT.tt" con "public class InfraestructureEntityRepositoryCT : Template"
//
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace Atento.Suite.Shared.Infrastructure
{

    using System;
    using Inflexion2;
    using Inflexion2.Domain;
    using Atento.Suite.Shared.Domain;
    using Atento.Suite.Shared.Domain.Data;
    using System.Data.Entity;
  
    /// <summary>
    /// Clase pública repositorio para persistir y 
    /// obtener información a partir de entidades <see cref="Persona"/>.
    /// </summary>
    /// <remarks>
    /// Sin comentarios adicionales.
    /// </remarks>
    public partial class PersonaRepository : EFRepository<Persona, Int32>, IPersonaRepository
    {

        #region constructors
        /// <summary>
        /// Inicializa una nueva instancia de la clase <see cref="PersonaRepository"/>.
        /// </summary>
        /// <remarks>
        /// el constructor ha de ser publico para poder ser resuelto por unity.
        /// </remarks>
        /// <param name="dbContext">
        /// Parámetro de tipo <see cref="DbContext"/> que hace referencia 
        /// a la unidad de trabajo para el acceso a datos.
        /// </param>
        /// <exception cref="System.ArgumentNullException">
        /// Lanzada cuando el valor del parámetro <c>dbContext</c> es null.
        /// </exception>
        public PersonaRepository(DbContext dbContext) : base(dbContext) 
        {
        } // PersonaRepository Constructor

        #endregion

    } // Persona

} // Atento.Suite.Shared.Infrastructure
