//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atento.Suite.Shared.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedNeutral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedNeutral() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atento.Suite.Shared.Infrastructure.Resources.SharedNeutral", typeof(SharedNeutral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Categoria_NameAlias {
            get {
                return ResourceManager.GetString("Categoria_NameAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Categoria_NameRemarks {
            get {
                return ResourceManager.GetString("Categoria_NameRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Categoria_NameTooltip {
            get {
                return ResourceManager.GetString("Categoria_NameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string CategoriaAlias {
            get {
                return ResourceManager.GetString("CategoriaAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clasificador.
        /// </summary>
        public static string CategoriaRemarks {
            get {
                return ResourceManager.GetString("CategoriaRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clasificación.
        /// </summary>
        public static string CategoriaTooltip {
            get {
                return ResourceManager.GetString("CategoriaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EnumeracionAlias {
            get {
                return ResourceManager.GetString("EnumeracionAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EnumeracionRemarks {
            get {
                return ResourceManager.GetString("EnumeracionRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EnumeracionTooltip {
            get {
                return ResourceManager.GetString("EnumeracionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_BooleanFieldAlias {
            get {
                return ResourceManager.GetString("Persona_BooleanFieldAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_BooleanFieldRemarks {
            get {
                return ResourceManager.GetString("Persona_BooleanFieldRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_BooleanFieldTooltip {
            get {
                return ResourceManager.GetString("Persona_BooleanFieldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_ByteFieldAlias {
            get {
                return ResourceManager.GetString("Persona_ByteFieldAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_ByteFieldRemarks {
            get {
                return ResourceManager.GetString("Persona_ByteFieldRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_ByteFieldTooltip {
            get {
                return ResourceManager.GetString("Persona_ByteFieldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_DatetimeFieldAlias {
            get {
                return ResourceManager.GetString("Persona_DatetimeFieldAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_DatetimeFieldRemarks {
            get {
                return ResourceManager.GetString("Persona_DatetimeFieldRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_DatetimeFieldTooltip {
            get {
                return ResourceManager.GetString("Persona_DatetimeFieldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_DateTimeOffsetFieldAlias {
            get {
                return ResourceManager.GetString("Persona_DateTimeOffsetFieldAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_DateTimeOffsetFieldRemarks {
            get {
                return ResourceManager.GetString("Persona_DateTimeOffsetFieldRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_DateTimeOffsetFieldTooltip {
            get {
                return ResourceManager.GetString("Persona_DateTimeOffsetFieldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_DecimalFieldAlias {
            get {
                return ResourceManager.GetString("Persona_DecimalFieldAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_DecimalFieldRemarks {
            get {
                return ResourceManager.GetString("Persona_DecimalFieldRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_DecimalFieldTooltip {
            get {
                return ResourceManager.GetString("Persona_DecimalFieldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_DobleFieldAlias {
            get {
                return ResourceManager.GetString("Persona_DobleFieldAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_DobleFieldRemarks {
            get {
                return ResourceManager.GetString("Persona_DobleFieldRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_DobleFieldTooltip {
            get {
                return ResourceManager.GetString("Persona_DobleFieldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_FloatFieldAlias {
            get {
                return ResourceManager.GetString("Persona_FloatFieldAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_FloatFieldRemarks {
            get {
                return ResourceManager.GetString("Persona_FloatFieldRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_FloatFieldTooltip {
            get {
                return ResourceManager.GetString("Persona_FloatFieldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_GuidFieldAlias {
            get {
                return ResourceManager.GetString("Persona_GuidFieldAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_GuidFieldRemarks {
            get {
                return ResourceManager.GetString("Persona_GuidFieldRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_GuidFieldTooltip {
            get {
                return ResourceManager.GetString("Persona_GuidFieldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_Int16FieldAlias {
            get {
                return ResourceManager.GetString("Persona_Int16FieldAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_Int16FieldRemarks {
            get {
                return ResourceManager.GetString("Persona_Int16FieldRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_Int16FieldTooltip {
            get {
                return ResourceManager.GetString("Persona_Int16FieldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_Int32FieldAlias {
            get {
                return ResourceManager.GetString("Persona_Int32FieldAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_Int32FieldRemarks {
            get {
                return ResourceManager.GetString("Persona_Int32FieldRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_Int32FieldTooltip {
            get {
                return ResourceManager.GetString("Persona_Int32FieldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_Int64FieldAlias {
            get {
                return ResourceManager.GetString("Persona_Int64FieldAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_Int64FieldRemarks {
            get {
                return ResourceManager.GetString("Persona_Int64FieldRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_Int64FieldTooltip {
            get {
                return ResourceManager.GetString("Persona_Int64FieldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_IntFieldAlias {
            get {
                return ResourceManager.GetString("Persona_IntFieldAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_IntFieldRemarks {
            get {
                return ResourceManager.GetString("Persona_IntFieldRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_IntFieldTooltip {
            get {
                return ResourceManager.GetString("Persona_IntFieldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_LongFieldAlias {
            get {
                return ResourceManager.GetString("Persona_LongFieldAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_LongFieldRemarks {
            get {
                return ResourceManager.GetString("Persona_LongFieldRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_LongFieldTooltip {
            get {
                return ResourceManager.GetString("Persona_LongFieldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_NombreAlias {
            get {
                return ResourceManager.GetString("Persona_NombreAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La propiedad&apos;Nombre&apos; de la clase &apos;Persona&apos; tiene un limite mínimo de longitud de  y un máximo de  &apos;.
        /// </summary>
        public static string Persona_NombreRangeStringLengthError {
            get {
                return ResourceManager.GetString("Persona_NombreRangeStringLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_NombreRemarks {
            get {
                return ResourceManager.GetString("Persona_NombreRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_NombreTooltip {
            get {
                return ResourceManager.GetString("Persona_NombreTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_ShortFieldAlias {
            get {
                return ResourceManager.GetString("Persona_ShortFieldAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_ShortFieldRemarks {
            get {
                return ResourceManager.GetString("Persona_ShortFieldRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_ShortFieldTooltip {
            get {
                return ResourceManager.GetString("Persona_ShortFieldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télefono.
        /// </summary>
        public static string Persona_TimeSpanFieldAlias {
            get {
                return ResourceManager.GetString("Persona_TimeSpanFieldAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_TimeSpanFieldRemarks {
            get {
                return ResourceManager.GetString("Persona_TimeSpanFieldRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Persona_TimeSpanFieldTooltip {
            get {
                return ResourceManager.GetString("Persona_TimeSpanFieldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string PersonaAlias {
            get {
                return ResourceManager.GetString("PersonaAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datos acerca de personas fisica y juridicas..
        /// </summary>
        public static string PersonaRemarks {
            get {
                return ResourceManager.GetString("PersonaRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositorio de personas físicas o juridicas..
        /// </summary>
        public static string PersonaTooltip {
            get {
                return ResourceManager.GetString("PersonaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Preference_KeyAlias {
            get {
                return ResourceManager.GetString("Preference_KeyAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Preference_KeyRemarks {
            get {
                return ResourceManager.GetString("Preference_KeyRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Preference_KeyTooltip {
            get {
                return ResourceManager.GetString("Preference_KeyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scopes.
        /// </summary>
        public static string Preference_ScopesAlias__ {
            get {
                return ResourceManager.GetString("Preference_ScopesAlias__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string Preference_TypesAlias__ {
            get {
                return ResourceManager.GetString("Preference_TypesAlias__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Preference_UserAlias_ {
            get {
                return ResourceManager.GetString("Preference_UserAlias_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Preference_ValueAlias {
            get {
                return ResourceManager.GetString("Preference_ValueAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Preference_ValueRemarks {
            get {
                return ResourceManager.GetString("Preference_ValueRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Preference_ValueTooltip {
            get {
                return ResourceManager.GetString("Preference_ValueTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string Preference_VisibleAlias {
            get {
                return ResourceManager.GetString("Preference_VisibleAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set the visibility and accesibility of this preference to the end user..
        /// </summary>
        public static string Preference_VisibleRemarks {
            get {
                return ResourceManager.GetString("Preference_VisibleRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is user visible?.
        /// </summary>
        public static string Preference_VisibleTooltip {
            get {
                return ResourceManager.GetString("Preference_VisibleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        public static string PreferenceAlias {
            get {
                return ResourceManager.GetString("PreferenceAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences or settings.
        /// </summary>
        public static string PreferenceRemarks {
            get {
                return ResourceManager.GetString("PreferenceRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences of application.
        /// </summary>
        public static string PreferenceTooltip {
            get {
                return ResourceManager.GetString("PreferenceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        public static string Scope_PreferenceAlias_ {
            get {
                return ResourceManager.GetString("Scope_PreferenceAlias_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        public static string ScopeAlias {
            get {
                return ResourceManager.GetString("ScopeAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the scope for the preference at level of application or only for one user.
        /// </summary>
        public static string ScopeRemarks {
            get {
                return ResourceManager.GetString("ScopeRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range of scope .
        /// </summary>
        public static string ScopeTooltip {
            get {
                return ResourceManager.GetString("ScopeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference2.
        /// </summary>
        public static string Type_Preference2Alias_ {
            get {
                return ResourceManager.GetString("Type_Preference2Alias_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TypeAlias {
            get {
                return ResourceManager.GetString("TypeAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TypeRemarks {
            get {
                return ResourceManager.GetString("TypeRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TypeTooltip {
            get {
                return ResourceManager.GetString("TypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os Name.
        /// </summary>
        public static string User_OsNameAlias {
            get {
                return ResourceManager.GetString("User_OsNameAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows user name.
        /// </summary>
        public static string User_OsNameRemarks {
            get {
                return ResourceManager.GetString("User_OsNameRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows user Name.
        /// </summary>
        public static string User_OsNameTooltip {
            get {
                return ResourceManager.GetString("User_OsNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string User_PreferencesAlias__ {
            get {
                return ResourceManager.GetString("User_PreferencesAlias__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserAlias {
            get {
                return ResourceManager.GetString("UserAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows user information..
        /// </summary>
        public static string UserRemarks {
            get {
                return ResourceManager.GetString("UserRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows user information..
        /// </summary>
        public static string UserTooltip {
            get {
                return ResourceManager.GetString("UserTooltip", resourceCulture);
            }
        }
    }
}
