
#region Copyright info
//-----------------------------------------------------------------------
// <copyright file="Address" company="Company">
//     Copyright (c) 2019. Company. All Rights Reserved.
//     Copyright (c) 2019. Company. Todos los derechos reservados.
//
//     .en This code has been generated by a tool, please don't modify this file or  
//     you will lost all your modifications in the next regeneration.
//      The original t4 template to get this file is " DomainBaseEntitySpecificationsCT.tt" with "public class DomainBaseEntitySpecificationsCT : Template"
// 
//     .es Este código ha sido generado por una herramienta, por favor no modifique este fichero
//     o perdera las modificaciones al regenerar este fichero.
//      La plantilla con que se ha generado este fichero es "DomainBaseEntitySpecificationsCT.tt" con "public class DomainBaseEntitySpecificationsCT : Template"
//
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace Needel.Common.Domain
{



    #region usings
    // en una clase parcial los using solo son necesarios una vez pero se dejan por si sirven de ayuda

    using System;
    using System.Linq;
    using Needel.Common.Domain;
    using Inflexion2.Domain;
    using Inflexion2;
    using Inflexion2.Domain.Specification;

    using System.ComponentModel.DataAnnotations;
    #endregion

    /// <summary>
    /// Clase que representa las especificaciones para la entidad <see cref="T:Address"/>.
    /// </summary>
    /// <remarks>
    /// Sin comentarios adicionales.
    /// </remarks>
    public static class AddressSpecifications
    {
        #region Address Basic Specifications

        // ha continuación se incorporan las especificaciones correspondientes a los campos marcados como filter o como identification
        
        #endregion

        #region Address Complex Specifications
        #endregion

    } // class Address

} //  Needel.Common.Domain

