#region Copyright info
//-----------------------------------------------------------------------
// <copyright file="AppSetting" company="Company">
//     Copyright (c) 2020. Company. All Rights Reserved.
//     Copyright (c) 2020. Company. Todos los derechos reservados.
//
//     .en This code has been generated by a tool, please don't modify this file or  
//     you will lost all your modifications in the next regeneration.
//      The original t4 template to get this file is " ApplicationEntityMapperCT.tt" with "public class ApplicationEntityMapperCT : Template"
// 
//     .es Este código ha sido generado por una herramienta, por favor no modifique este fichero
//     o perdera las modificaciones al regenerar este fichero.
//      La plantilla con que se ha generado este fichero es "ApplicationEntityMapperCT.tt" con "public class ApplicationEntityMapperCT : Template"
//
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace Needel.Common.Application
{

    #region usings
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Inflexion2;

    using Needel.Common.Application.Dtos;
    using Needel.Common.Domain;
    #endregion

    /// <summary>
    /// .en mapping class from Entity to dto <see cref="AppSettingMapper"/>
    /// .es Clase pública encargada de mapear los datos de una entidad <see cref="AppSettingMapper"/>.
    /// </summary>
    public class AppSettingMapper : IAppSettingMapper
    {
        #region Fields parent mappers
        #endregion

        #region Fields children mappers
        #endregion

        #region CONSTRUCTORS
        /// <summary>
        /// .en Get an instance of <see cref="AppSettingMapper"/>
        /// .es Inicializa una nueva instancia de la clase <see cref="AppSettingMapper"/>.
        /// </summary>
        public AppSettingMapper()
        {
        }
        #endregion

        #region Properties parent mappers
        #endregion

        #region Properties children mappers
        #endregion

        #region FUNCTIONS
        /// <summary>
        /// Default constructor parameters
        /// </summary>
        /// <param name="entityAppSetting"></param>
        /// <returns></returns>
        public AppSettingDto EntityMapping(AppSetting entityAppSetting)
        {
            if (entityAppSetting == null)
            {
                return null;
            }

            return EntityMapping(entityAppSetting, true, false);
        }

        /// <summary>
        /// .en public function mapping from Entity to dto
        /// </summary>
        /// <param name="entityAppSetting">
        /// </param>
        /// <param name="mapParents">
        /// .en option to map parent objects
        /// </param>
        /// <param name="mapChildren">
        /// .en option to map children objects
        /// </param>
        /// <returns>
        /// .en returns an DTO of type <see cref="AppSettingDto"/>
        /// </returns>
        public AppSettingDto EntityMapping(AppSetting entityAppSetting, bool mapParents , bool mapChildren)
        {
            if (entityAppSetting == null)
            {
                return null;
            }

            AppSettingDto dtoAppSetting = new AppSettingDto();
            dtoAppSetting.Id = entityAppSetting.Id;
            dtoAppSetting.Key = entityAppSetting.Key;
            dtoAppSetting.Value = entityAppSetting.Value;
            dtoAppSetting.Remark = entityAppSetting.Remark;

            if (mapParents)
            {
            dtoAppSetting.AppSettingType = entityAppSetting.AppSettingType;
            }

            return dtoAppSetting;
        } // EntityMapping
        #endregion
    } // end class AppSettingMapper
} //  Needel.Common.Application
