#region Copyright info
//-----------------------------------------------------------------------
// <copyright file="Persona" company="Atento">
//     Copyright (c) 2016. Atento. All Rights Reserved.
//     Copyright (c) 2016. Atento. Todos los derechos reservados.
//
//     .en This code has been generated by a tool, please don't modify this file or  
//     you will lost all your modifications in the next regeneration.
//      The original t4 template to get this file is " DomainCoreIEntityCT.tt" with "public class DomainCoreIEntityCT : Template"
// 
//     .es Este código ha sido generado por una herramienta, por favor no modifique este fichero
//     o perdera las modificaciones al regenerar este fichero.
//      La plantilla con que se ha generado este fichero es "DomainCoreIEntityCT.tt" con "public class DomainCoreIEntityCT : Template"
//
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace Atento.Suite.Shared.Domain
{


    #region Usings
    using System;
    using Atento.Suite.Shared.Domain.Data;
    using Inflexion2.Domain;
    using Inflexion2;
    
    #endregion

    /// <summary>
    /// .en Interfaz to identify an entidad of type Persona in the application.
    /// .es Interfaz que identifica una entidad de tipo Persona de la aplicación.
    /// datos acerca de personas fisica y juridicas.
    /// </summary>
    /// <remarks>
    /// .en Interfaz for an Entity implemented by Persona/>.
    /// .es Interfaz que representa  una entidad implementado enPersona/>.
    /// </remarks>
    public interface IPersona : 	Inflexion2.Domain.IAggregateRoot<IPersona, Int32> 	
    {

        #region Properties
        /// <summary>
        /// .en Property to get & set Nombre.
        /// .es Propiedad que permite obtener y establecer Nombre.
        /// </summary>
        /// <remarks>
        /// Test with auto property and public setter.
        /// </remarks>
        /// <value>
        /// .en Value used to get & set Nombre.
        /// .es Valor que es utilizado para obtener y establecer Nombre.
        /// </value>
        string Nombre { get; set; }
        /// <summary>
        /// .en Property to get & set BooleanField.
        /// .es Propiedad que permite obtener y establecer BooleanField.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <value>
        /// .en Value used to get & set BooleanField.
        /// .es Valor que es utilizado para obtener y establecer BooleanField.
        /// </value>
        bool BooleanField { get; set; }
        /// <summary>
        /// .en Property to get & set DatetimeField.
        /// .es Propiedad que permite obtener y establecer DatetimeField.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <value>
        /// .en Value used to get & set DatetimeField.
        /// .es Valor que es utilizado para obtener y establecer DatetimeField.
        /// </value>
        DateTime DatetimeField { get; set; }
        /// <summary>
        /// .en Property to get & set ByteField.
        /// .es Propiedad que permite obtener y establecer ByteField.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <value>
        /// .en Value used to get & set ByteField.
        /// .es Valor que es utilizado para obtener y establecer ByteField.
        /// </value>
        byte ByteField { get; set; }
        /// <summary>
        /// .en Property to get & set GuidField.
        /// .es Propiedad que permite obtener y establecer GuidField.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <value>
        /// .en Value used to get & set GuidField.
        /// .es Valor que es utilizado para obtener y establecer GuidField.
        /// </value>
        Guid GuidField { get; set; }
        /// <summary>
        /// .en Property to get & set DecimalField.
        /// .es Propiedad que permite obtener y establecer DecimalField.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <value>
        /// .en Value used to get & set DecimalField.
        /// .es Valor que es utilizado para obtener y establecer DecimalField.
        /// </value>
        decimal DecimalField { get; set; }
        /// <summary>
        /// .en Property to get & set DobleField.
        /// .es Propiedad que permite obtener y establecer DobleField.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <value>
        /// .en Value used to get & set DobleField.
        /// .es Valor que es utilizado para obtener y establecer DobleField.
        /// </value>
        double DobleField { get; set; }
        /// <summary>
        /// .en Property to get & set FloatField.
        /// .es Propiedad que permite obtener y establecer FloatField.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <value>
        /// .en Value used to get & set FloatField.
        /// .es Valor que es utilizado para obtener y establecer FloatField.
        /// </value>
        float FloatField { get; set; }
        /// <summary>
        /// .en Property to get & set IntField.
        /// .es Propiedad que permite obtener y establecer IntField.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <value>
        /// .en Value used to get & set IntField.
        /// .es Valor que es utilizado para obtener y establecer IntField.
        /// </value>
        int IntField { get; set; }
        /// <summary>
        /// .en Property to get & set LongField.
        /// .es Propiedad que permite obtener y establecer LongField.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <value>
        /// .en Value used to get & set LongField.
        /// .es Valor que es utilizado para obtener y establecer LongField.
        /// </value>
        long LongField { get; set; }
        /// <summary>
        /// .en Property to get & set DateTimeOffsetField.
        /// .es Propiedad que permite obtener y establecer DateTimeOffsetField.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <value>
        /// .en Value used to get & set DateTimeOffsetField.
        /// .es Valor que es utilizado para obtener y establecer DateTimeOffsetField.
        /// </value>
        DateTimeOffset DateTimeOffsetField { get; set; }
        /// <summary>
        /// .en Property to get & set ShortField.
        /// .es Propiedad que permite obtener y establecer ShortField.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <value>
        /// .en Value used to get & set ShortField.
        /// .es Valor que es utilizado para obtener y establecer ShortField.
        /// </value>
        short ShortField { get; set; }
        /// <summary>
        /// .en Property to get & set TimeSpanField.
        /// .es Propiedad que permite obtener y establecer TimeSpanField.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <value>
        /// .en Value used to get & set TimeSpanField.
        /// .es Valor que es utilizado para obtener y establecer TimeSpanField.
        /// </value>
        TimeSpan TimeSpanField { get; set; }
        /// <summary>
        /// .en Property to get & set Int16Field.
        /// .es Propiedad que permite obtener y establecer Int16Field.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <value>
        /// .en Value used to get & set Int16Field.
        /// .es Valor que es utilizado para obtener y establecer Int16Field.
        /// </value>
        Int16 Int16Field { get; set; }
        /// <summary>
        /// .en Property to get & set Int32Field.
        /// .es Propiedad que permite obtener y establecer Int32Field.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <value>
        /// .en Value used to get & set Int32Field.
        /// .es Valor que es utilizado para obtener y establecer Int32Field.
        /// </value>
        Int32 Int32Field { get; set; }
        /// <summary>
        /// .en Property to get & set Int64Field.
        /// .es Propiedad que permite obtener y establecer Int64Field.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <value>
        /// .en Value used to get & set Int64Field.
        /// .es Valor que es utilizado para obtener y establecer Int64Field.
        /// </value>
        Int64 Int64Field { get; set; }
        #endregion

        #region Methods
        #endregion

    } // End class Persona.

} // End NameSpace Atento.Suite.Shared.Domain.
