//-----------------------------------------------------------------------
// <copyright file="Persona" company="Atento">
//     Copyright (c) 2016. Atento. All Rights Reserved.
//     Copyright (c) 2016. Atento. Todos los derechos reservados.
//
//     .en This code has been generated by a tool, please don't modify this file or  
//     will lost all your modifications in the process to regenerate.
//      The original t4 template to get this file is " ApplicationEntityDtoCT.tt" with "public class ApplicationEntityDtoCT : Template"
// 
//     .es Este código ha sido generado por una herramienta, por favor no modifique este fichero
//     o perdera las modificaciones al regenerar este fichero.
//      La plantilla con que se ha generado este fichero es "ApplicationEntityDtoCT.tt" con "public class ApplicationEntityDtoCT : Template"
//
// </copyright>
//-----------------------------------------------------------------------

namespace Atento.Suite.Shared.Application.Dtos
{

    #region SharedKernel usings
    #endregion

    #region usings
    using System;
    using System.Runtime.Serialization;
    using Inflexion2.Application.DataTransfer.Base;

    using Atento.Suite.Shared.Domain.Data;
    #endregion

    /// <summary>
    /// Clase que representa a la entidad <see cref="PersonaDto"/>.
    /// </summary>
    /// <remarks>
    /// Crea un objeto <see cref="PersonaDto"/>.
    /// </remarks>
    // no tiene subclases
    // no tiene superclases
    [DataContract]
    public  class PersonaDto : BaseEntityDataTransferObject<Int32> 
    {
       #region CONSTRUCTORS
        
        /// <summary>
        /// Inicializa una nueva instancia de la clase <see cref="PersonaDto"/>.
        /// </summary>
        /// <remarks>
        /// Constructor de la clase <see cref="PersonaDto"/>.
        /// </remarks>
        public PersonaDto()
        {
        } // PersonaDto Constructor

       #endregion

       #region PROPERTIES

        /// <summary>
        /// Variable privada que identifica Nombre.
        /// </summary>
        /// <remarks>
        /// Test with auto property and public setter.
        /// </remarks>
        [DataMember]
        public string Nombre {get; set;}

        /// <summary>
        /// Variable privada que identifica Juridica.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public bool Juridica {get; set;}

        /// <summary>
        /// Variable privada que identifica Direccion.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public string Direccion {get; set;}

        /// <summary>
        /// Variable privada que identifica Calle.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public string Calle {get; set;}

        /// <summary>
        /// Variable privada que identifica CP.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public string CP {get; set;}

        /// <summary>
        /// Variable privada que identifica Provincia.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public string Provincia {get; set;}

        /// <summary>
        /// Variable privada que identifica Comunidad.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public string Comunidad {get; set;}

        /// <summary>
        /// Variable privada que identifica Pais.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public string Pais {get; set;}

        /// <summary>
        /// Variable privada que identifica Matricula.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public string Matricula {get; set;}

        /// <summary>
        /// Variable privada que identifica Codigo.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public string Codigo {get; set;}

        /// <summary>
        /// Variable privada que identifica Sector.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public string Sector {get; set;}

        /// <summary>
        /// Variable privada que identifica Site.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public string Site {get; set;}

        /// <summary>
        /// Variable privada que identifica LogoImagen.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public string LogoImagen {get; set;}

        /// <summary>
        /// Variable privada que identifica Telefono.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public string Telefono {get; set;}

        /// <summary>
        /// Variable privada que identifica Fax.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public string Fax {get; set;}

        /// <summary>
        /// Variable privada que identifica Mobil.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public string Mobil {get; set;}

        /// <summary>
        /// Variable privada que identifica Atributte1.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public string Atributte1 {get; set;}

        /// <summary>
        /// Variable privada que identifica FormaJuridica.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public string FormaJuridica {get; set;}

        /// <summary>
        /// Variable privada que identifica fisica.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public bool Fisica {get; set;}

        /// <summary>
        /// Variable privada que identifica Genero.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public string Genero {get; set;}
        #endregion

    } // end class PersonaDto
} //  Atento.Suite.Shared.Application.Dtos

