
#region Copyright info
//-----------------------------------------------------------------------
// <copyright file="Address" company="Company">
//     Copyright (c) 2019. Company. All Rights Reserved.
//     Copyright (c) 2019. Company. Todos los derechos reservados.
//
//     .en This code has been generated by a tool, please don't modify this file or  
//     you will lost all your modifications in the next regeneration.
//      The original t4 template to get this file is " WpfEntityViewModelCT.tt" with "public class WpfEntityViewModelCT : Template"
// 
//     .es Este código ha sido generado por una herramienta, por favor no modifique este fichero
//     o perdera las modificaciones al regenerar este fichero.
//      La plantilla con que se ha generado este fichero es "WpfEntityViewModelCT.tt" con "public class WpfEntityViewModelCT : Template"
//
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace Needel.Common.FrontEnd.WpfModule
{

    #region usings   
    using System;
    using System.Collections.ObjectModel;
    using System.Collections.Generic;
    using System.Linq;
    using System.ServiceModel;
    using System.Windows.Input;

    using MvvmValidation;
    using Needel.Common.Domain.Data;
    using Needel.Common.Application;
    using Needel.Common.Application.Dtos;
    using Needel.Common.Infrastructure.Resources;
    using Needel.Common.Application.WcfClient.AddressReference;

    using Inflexion2.Application;
    using Inflexion2.UX.WPF.MVVM.Commands;
    using Microsoft.Practices.Prism.Commands;
    using Microsoft.Practices.Prism.Events;
    #endregion

    /// <summary>
    /// .en Interaction logic for AddressViewModel.xaml
    /// .es Logica de interación para la vista AddressViewModel.xaml
    /// </summary>
    public partial class AddressViewModel : Inflexion2.UX.WPF.MVVM.CRUD.CrudViewModel<AddressDto, Int32>
    {
        #region Fields


        #endregion

        #region Constructors
        /// <summary>
        /// .en Initialize a new instace for the class <see cref="T:AddressViewModel"/>.
        /// .es Inicializa una nueva instancia de la clase <see cref="T:AddressViewModel"/>.
        /// </summary>
        public AddressViewModel() : base()
        {
            Initialization();
        } // AddressViewModel Constructor

        private void Initialization()
        {
            // .en https://github.com/SeriousM/WPFLocalizationExtension/issues/87#issuecomment-174510689
            // bind the property title of the VM to a dependecy property for the view. To allow the localization of the property tittle.
            // becouse this property don´t belong the class AddressControl what is the base for the view
            // but avalon dock uses this property to set the title of the dockable elements
            // if we wont tha this can be updated when the selected culture is changed we need this work arround.
            var targetProperty = this.GetType().GetProperty(nameof(AddressQueryViewModel.Title));
            var locBinding = new WPFLocalizeExtension.Extensions.LocTextExtension("AddressAlias");
            locBinding.SetBinding(this, targetProperty);

            // .en after to bind the property with the depdendecy property watch if theres is a change of the 
            // the culture to raise an event to warning that the title property has changed
            WPFLocalizeExtension.Engine.LocalizeDictionary.Instance.PropertyChanged += (sender, e) =>
            {
                if (e.PropertyName == "Culture")
                {
                    this.RaisePropertyChanged(() => Title);
                }
            };
        } // AddressViewModel intialization
        /// <summary>
        /// .es Inicializa una nueva instancia de la clase <see cref="T:UserViewModel"/>.
        /// Este constructor es invocado por primera vez desde el QueryViewModel ya que para cada 
        /// linea que se visualiza en la lista de Usuarios se crea el Viewmodel de dicho usuario.
        /// Esta lista se almacena en una observable collection en el query view model con la que se hace el binding 
        /// de la pantalla query.
        /// Por esta razon las entidades relacionadas no se cargan si no se navega hasta esta entidad.
        /// </summary>
        /// <param name="element">
        /// Parámetro de tipo <see cref="AddressDto"/> que contiene la información necesaria.
        /// </param>
        public AddressViewModel(AddressDto element)
            :  base(element)
        {
            Initialization();
        } // AddressViewModel Parametrized Constructor

        #endregion

        #region Properties

        /// <summary>
        /// .es Propiedad para establecer el Título de la ventana cuando este view model se utiliza 
        /// en un control de usuario o ventana exclusivamente para el.
        /// cuando este view model se utiliza solo en una lista esta propiedad no se utiliza.
        /// </summary>
        public override string Title{ get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string StreetName
        {
            get
            {
                return this.ObjectElement.StreetName;
            }
            set
            {
                if (this.ObjectElement.StreetName != value)
                {
                    this.ObjectElement.StreetName  = value;
                    this.RaisePropertyChanged(() => this.StreetName);
                }
            }
        } // StreetName
        /// <summary>
        /// 
        /// </summary>
        public string BuildingNumber
        {
            get
            {
                return this.ObjectElement.BuildingNumber;
            }
            set
            {
                if (this.ObjectElement.BuildingNumber != value)
                {
                    this.ObjectElement.BuildingNumber  = value;
                    this.RaisePropertyChanged(() => this.BuildingNumber);
                }
            }
        } // BuildingNumber

        #endregion

        #region Properties from Parents
        // .en collections to select parent properties.
        // .es colecciones para seleccionar propiedades parentales.

        #endregion

        #region Methods

        /// <summary>.es Obtener el dto de la entidad Address por su identificador.</summary>
        /// <param name="identifier">.es Parámetro que indica el identificador de la entidad que se va a recuperar.</param>
        /// <returns>.es Devuelve el objeto Dto <see cref="AddressDto"/> correspondiente.</returns>
        public override AddressDto GetById(Int32 identifier)
        {
            AddressServiceClient serviceClient = new AddressServiceClient();
            // .en consume the service and get the data // .es Consumimos el servicio y obtenemos los datos.
            var addressDto = serviceClient.GetById(identifier );

            return addressDto;
        } // GetById

        /// <summary>.es Crear o actualizar una entidad de tipo Address.</summary>
        /// <param name="parameter">data to update.</param>
        public override void OnSaveRecord(object parameter)
        {
            if (this.IsActive &&
                    (this.ObjectElement != null))
            {
                
                AddressServiceClient serviceClient = new AddressServiceClient();

                if (this.ObjectElement.Id == default(Int32) )
                {
                    serviceClient.Create(this.ObjectElement);
                    this.MessageBoxService.Show("Entidad agregada");
                }
                else
                {
                    bool response = serviceClient.Update(this.ObjectElement);
                    this.MessageBoxService.Show("Entidad actualizada");
                }

                UpdateParentView();
            }
        } // OnSaveRecord

        /// <summary>.en Create a new Address</summary>
        /// <param name="parameter">.en Data to create the new Address</param>
        public override void OnNewRecord(object parameter)
        {
            var views = this.RegionManager.Regions[Inflexion2.UX.WPF.MVVM.RegionNames.WorkspaceRegion].ActiveViews;
            base.OnNewRecord(parameter);
            this.Initialization();
            AddressView currentView = (AddressView)views.FirstOrDefault();

        }

        #endregion

        #region Protected Methods


        /// <summary>
        /// example to execute validation rules
        /// </summary>
        /// <param name="validation"></param>
        protected override void SetupValidation(MvvmValidation.ValidationHelper validation)
        {
            //ejemplo de validacion
            //// Validación de hora de Inicio
            //validation.AddRule(
            //                   () => this.propiedad,
            //                   () => RuleResult.Assert(
            //                                           this.propiedad != null,
            //                                           "mensaje"));

        }

        /// <summary>
        /// .en Here is possible to override the actions to execute when there is a navigation request
        /// </summary>
        /// <remarks>
        /// .en Here is where to call to the methods to load the related entities (children and parents).
        /// .es aqui es donde se invoca a los métodos de carga de las entidades adicionales.
        /// </remarks>
        public override void OnNavigatedTo(Microsoft.Practices.Prism.Regions.NavigationContext navigationContext)
        {
            base.OnNavigatedTo(navigationContext);

            this.Rebind();
        }

        #endregion
    }
} //  Needel.Common.FrontEnd.WpfModule
