
#region Copyright info
//-----------------------------------------------------------------------
// <copyright file="User" company="Company">
//     Copyright (c) 2020. Company. All Rights Reserved.
//     Copyright (c) 2020. Company. Todos los derechos reservados.
//
//     .en This code has been generated by a tool, please don't modify this file or  
//     you will lost all your modifications in the next regeneration.
//      The original t4 template to get this file is " WpfEntityViewModelCT.tt" with "public class WpfEntityViewModelCT : Template"
// 
//     .es Este código ha sido generado por una herramienta, por favor no modifique este fichero
//     o perdera las modificaciones al regenerar este fichero.
//      La plantilla con que se ha generado este fichero es "WpfEntityViewModelCT.tt" con "public class WpfEntityViewModelCT : Template"
//
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace Needel.Common.FrontEnd.WpfModule
{

    #region usings   
    using System;
    using System.Collections.ObjectModel;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using System.ServiceModel;
    using System.Windows;
    using System.Windows.Input;

    using MvvmValidation;
    using Needel.Common.Domain.Data;
    using Needel.Common.Application;
    using Needel.Common.Application.Dtos;
    using Needel.Common.Infrastructure.Resources;
    using Needel.Common.Application.WcfClient.UserReference;
    using Needel.Common.Application.WcfClient.DepartmentReference; //property parent
    using Needel.Common.Application.WcfClient.AddressReference; //property children

    using Inflexion2.Domain.Data;
    using Inflexion2.Application;
    using Inflexion2.Resources;
    using Inflexion2.UX.WPF.MVVM;
    using Inflexion2.UX.WPF.MVVM.Commands;
    using Microsoft.Practices.Prism.Commands;
    using Microsoft.Practices.Prism.Events;
    #endregion

    /// <summary>
    /// .en Interaction logic for UserViewModel.xaml
    /// .es Logica de interación para la vista UserViewModel.xaml
    /// </summary>
    public partial class UserViewModel : Inflexion2.UX.WPF.MVVM.CRUD.CrudViewModel<UserDto, Int32>, IEditableObject
    {
        #region Fields

        /// <summary>
        /// Campo para indicar que el viewmodel esta embevido en un viewmodel parental con el objeto de 
        /// de asegurar que se añade al menos un registro en esta entidad cuando se crea el padre de esta.
        /// </summary>
        bool from1VM;

        private AddressQueryViewModel addressesQueryVM;
        private AddressViewModel address1VM;
        private DepartmentQueryViewModel allUserDepartmentQueryVM;//*From sources no es reflexiva no es Many 2 Many
        private ObservableCollection<DepartmentDto> departmentsCombo;//**# no es reflexiva no es Many 2 Many
        private DepartmentQueryViewModel allDepartmentsQueryVM;//**#
        bool userDepartmentVisible = false;//**#
        private bool departmentComboVisible = false;//**#
        #endregion

        #region Constructors
        /// <summary>
        /// .en Parameterless constructor to implement the "IEditable" interface in query viewmodels that allow "editable row"
        /// </summary>
        public UserViewModel() : this(true)
        {
        }

        /// <summary>
        /// .en Initialize a new instace for the class <see cref="T:UserViewModel"/>.
        /// .es Inicializa una nueva instancia de la clase <see cref="T:UserViewModel"/>.
        /// </summary>
        public UserViewModel(bool from1VM = false) : base()
        {
            this.from1VM = from1VM;
            Initialization();
        } // UserViewModel Constructor

        public override void Initialization(UserDto element = null)
        {
            // .en https://github.com/SeriousM/WPFLocalizationExtension/issues/87#issuecomment-174510689
            // bind the property title of the VM to a dependecy property for the view. To allow the localization of the property tittle.
            // becouse this property don´t belong the class UserControl what is the base for the view
            // but avalon dock uses this property to set the title of the dockable elements
            // if we wont tha this can be updated when the selected culture is changed we need this work arround.
            var targetProperty = this.GetType().GetProperty(nameof(UserQueryViewModel.Title));
            var locBinding = new WPFLocalizeExtension.Extensions.LocTextExtension("UserAlias");
            locBinding.SetBinding(this, targetProperty);
            this.CurrentViewName = "UserView";
            // .en after to bind the property with the depdendecy property watch if theres is a change of the 
            // the culture to raise an event to warning that the title property has changed
            WPFLocalizeExtension.Engine.LocalizeDictionary.Instance.PropertyChanged += (sender, e) =>
            {
                if (e.PropertyName == "Culture")
                {
                    this.RaisePropertyChanged(() => Title);
                }
            };

            if ((this.ObjectElement != null && element != null && !this.ObjectElement.Equals(element)) || (this.ObjectElement == null && element != null))
            {
                this.ObjectElement = element;
            }

        } // UserViewModel initialization

        /// <summary>
        /// .en Child composed constructor <see cref="T:UserViewModel"/>.
        /// This constructor is used to be the viewmodel of a nested viemodel in a hierchahy.
        /// </summary>
        /// <param name="element">
        /// .en Parameter of type <see cref="UserDto"/> with all the related data.</param>
        /// <param name="first">first element in the current paged collection</param>
        /// <param name="previous">last element in the current paged collection</param>
        /// <param name="next">next element in the current paged collection</param>
        /// <param name="last">last element in the current paged collection</param>
        /// <remarks>
        /// .en these initialization are to allow navigation betwen pages and not only next record. TODO: test this.
        /// </remarks>
        public UserViewModel(UserDto element, UserDto first, UserDto previous, UserDto next, UserDto last)
            : base(element)
        {
            this.firstEntityId = first != null ? first.Id: default(Int32);
            this.nextEntityId = next != null ? next.Id : default(Int32);
            this.lastEntityId = last != null ? last.Id : default(Int32);
            this.previousEntityId = previous != null ? previous.Id : default(Int32);
            
            Initialization(element);

        } // UserViewModel Parametrized Constructor


        /// <summary>
        /// .es Inicializa una nueva instancia de la clase <see cref="T:UserViewModel"/>.
        /// Este constructor se invoca desde el QueryViewModel ya que para cada 
        /// linea que se visualiza en la lista de Usuarios se crea el Viewmodel de dicho usuario.
        /// Esta lista se almacena en una observable collection en el query view model con la que se hace el binding 
        /// de la pantalla query.
        /// Por esta razon las entidades relacionadas no se cargan si no se navega hasta esta entidad.
        /// </summary>
        /// <param name="element">
        /// Parámetro de tipo <see cref="UserDto"/> que contiene la información necesaria.
        /// </param>
        public UserViewModel(UserDto element, bool simpleViewModel = true)
            :  base(element)
        {
            if (!simpleViewModel)
            {
                Initialization(element);
            }
        } // UserViewModel Parametrized Constructor

        #endregion

        #region Properties

        /// <summary>
        /// Field to explain the meaning of this key
        /// </summary>
        public string Name
        {
            get
            {
                return this.ObjectElement.Name;
            }
            set
            {
                if (this.ObjectElement.Name != value)
                {
                    this.ObjectElement.Name  = value;
                    this.RaisePropertyChanged(() => this.Name);
                }
            }
        } // Name

        #endregion

        #region Properties from Parents

        // .en wrappers to help the managment of parent entities and their collections

        /// <summary>
        /// Campo para indicar que el viewmodel esta embebido en un viewmodel parental con el objeto de 
        /// de asegurar que se añade al menos un registro en esta entidad cuando se crea el padre de esta.
        /// </summary>
        public bool From1VM
        {
            get
            {
                return from1VM;
            }
        }

    #region UI controls visibility to manage parent properties in the view 
    public Visibility DepartmentVisibility            { get { return  userDepartmentVisible      ? Visibility.Visible : Visibility.Collapsed; } }
    public Visibility DepartmentComboBoxVisibility    { get { return  departmentComboVisible ? Visibility.Visible : Visibility.Collapsed; } }
    public Visibility DepartmentTextBoxVisibility     { get { return !departmentComboVisible ? Visibility.Visible : Visibility.Collapsed; } }
    #endregion


        /// <summary>
        /// Wraper property to help binding  
        /// </summary>
        public DepartmentDto UserDepartment
        {
            get
            {
                return this.ObjectElement.UserDepartment;
            }
            set
            {
                if (this.ObjectElement.UserDepartment != value)
                {
                    if (value == null || value.IsTransient())
                    {
                        this.ObjectElement.UserDepartment = null;
                    }
                    else
                    {
                        this.ObjectElement.UserDepartment = value;
                    }

                    this.RaisePropertyChanged(() => this.UserDepartment);
                }
            }
        } // UserDepartment

        /// <summary>
        /// .en Collection where to chose one parent from combobox for collections smaller than 50
        /// </summary>
        public ObservableCollection<DepartmentDto> DepartmentsCombo
        {
            get
            {
                return this.departmentsCombo;
            }
            set
            {
                if (this.departmentsCombo != value)
                {
                    this.departmentsCombo = value;
                }
            }
        }
        /// <summary>
        /// .en Collection where to chose one parent from datagrid for collections greater than 50
        /// </summary>
        public DepartmentQueryViewModel AllDepartmentsQueryVM
        {
            get
            {
                return allDepartmentsQueryVM;
            }
            set
            {
                if (this.allDepartmentsQueryVM != value)
                {
                    this.allDepartmentsQueryVM = value;
                    this.allDepartmentsQueryVM.ParentViewName = this.CurrentViewName;
                    this.allDepartmentsQueryVM.Title = "DepartmentQueryViewModel";
                    this.RaisePropertyChanged(() => this.AllDepartmentsQueryVM);
                }
            }
        }

        #endregion

        #region Properties from Children

        /// <summary>
        /// Property helper to allow easy access to the children properties
        /// </summary>
        public System.Collections.Generic.List<AddressDto> Addresses
        {
            get
            {
                return this.ObjectElement.Addresses;
            }
            set
            {
                if (this.ObjectElement.Addresses != value)
                {
                    if (value == null )
                    {
                        this.ObjectElement.Addresses = null;
                    }
                    else
                    {
                        this.ObjectElement.Addresses = value;
                    }

                    this.RaisePropertyChanged(() => this.Addresses);
                }
            }
        } // Addresses

        /// <summary>
        /// 
        /// </summary>
        public AddressQueryViewModel AddressesQueryVM
        {
            get
            {
                return addressesQueryVM;
            }
            set
            {
                if (this.addressesQueryVM != value)
                {
                    this.addressesQueryVM = value;
                    this.addressesQueryVM.ParentViewName = this.CurrentViewName;
                    this.addressesQueryVM.Title = "AddressesQueryVM";
                    this.RaisePropertyChanged(() => this.AddressesQueryVM);
                }
            }
        } // AddressesQueryViewModel

          
        /// <summary>
        /// 
        /// </summary>
        public AddressViewModel Address1VM
        {
            get
            {
                return address1VM;
            }
            set
            {
                if (this.address1VM != value)
                {
                    this.address1VM = value;
                    this.RaisePropertyChanged(() => this.Address1VM);
                }
            }
        } // Address1VM
        /// <summary>
        /// collection for drag and drop
        /// </summary>
        public DepartmentQueryViewModel AllUserDepartmentQueryVM
        {
            get
            {
                return allUserDepartmentQueryVM;
            }
            set
            {
                if (this.allUserDepartmentQueryVM != value)
                {
                    this.allUserDepartmentQueryVM = value;
                    this.allUserDepartmentQueryVM.Title = "AllUserDepartment"; //mark the viewmodel to facilitate the drag&drop
                    this.allUserDepartmentQueryVM.ParentViewName = this.CurrentViewName;
                    // todo: add a reference to parentviewmodel = this;
                    this.RaisePropertyChanged(() => this.AllUserDepartmentQueryVM);
                }
            }
        } // UserDepartment
        #endregion

        #region Methods
        /// <summary>.es Obtener el dto de la entidad User por su identificador.</summary>
        /// <param name="identifier">.es Parámetro que indica el identificador de la entidad que se va a recuperar.</param>
        /// <returns>.es Devuelve el objeto Dto <see cref="UserDto"/> correspondiente.</returns>
        public override UserDto GetById(Int32 identifier)
        {
            UserServiceClient serviceClient = new UserServiceClient();
            // .en consume the service and get the data // .es Consumimos el servicio y obtenemos los datos.
            var userDto = serviceClient.GetById(identifier );

            return userDto;
        } // GetById

        /// <summary>.es Crear o actualizar una entidad de tipo User.</summary>
        /// <param name="parameter">data to update.</param>
        public override void OnSaveRecord(object parameter)
        {
            if (this.IsActive && this.ObjectElement != null)
            {
                if (this.IsTransient)
                {
                    this.ObjectElement.Addresses.Add(this.address1VM.ObjectElement);
                }

                UserServiceClient serviceClient = new UserServiceClient();
                if (this.ObjectElement.Id == default(Int32) )
                {
                    serviceClient.Create(this.ObjectElement);
                    this.MessageBoxService.Show(FrameworkResource.AddedSuccessfullyEntity);
                }
                else
                {
                    bool response = serviceClient.Update(this.ObjectElement);
                    this.MessageBoxService.Show(FrameworkResource.UpdatedSuccessfullyEntity);
                }

                UpdateParentView();
            }
        }

        /// <summary>.en Create a new User</summary>
        /// <param name="parameter">.en Data to create the new User</param>
        public override void OnNewRecord(object parameter)
        {
            var views = this.RegionManager.Regions[Inflexion2.UX.WPF.MVVM.RegionNames.WorkspaceRegion].ActiveViews;
            base.OnNewRecord(parameter);
            this.Initialization();
            UserView currentView = (UserView)views.FirstOrDefault(c => c as UserView != null);

            // .en Nested Query view models for the controls of children properties or Many to Many.
            // .es View models anidados para los controles de colecciones de propiedades correspondientes a los hijos.
            (currentView.AddressesQueryView).DataContext = new AddressQueryViewModel();
            ((AddressQueryViewModel)(currentView.AddressesQueryView).DataContext).RefreshItems();//*

        }

        #endregion

        #region Protected Methods
        // .en implement here the loading of related entities or value objects.
        // .es implementar aqui los metodos de carga  de entidades u objetos valor relacionadas al root aggregate.

        private void PopulateDepartments(Int32 filterId, EnumPopulationType populationMethod = EnumPopulationType.All)
        {
            DepartmentServiceClient serviceClient = new DepartmentServiceClient();
            userDepartmentVisible = true;

            if (this.DepartmentsCombo != null && this.DepartmentsCombo.Count() > 0)
            {
                this.DepartmentsCombo.Clear();
            }

            if (filterId.Equals(default(Int32)) && populationMethod.HasFlag(EnumPopulationType.All))
            {
                this.DepartmentsCombo = serviceClient.GetAll();
            }
            else if (populationMethod.HasFlag(EnumPopulationType.AllExceptOwnId))
            {
                this.DepartmentsCombo = serviceClient.GetAllExceptThis(filterId); // Get All except the own Id to avoid a self reference object
            }
            else if (populationMethod.HasFlag(EnumPopulationType.OnlyId))
            {
                if (this.UserDepartment != null && this.UserDepartment.Id == filterId)
                {
                    this.departmentsCombo = new ObservableCollection<DepartmentDto>() { this.UserDepartment };
                }
                else
                {
                    this.UserDepartment = serviceClient.GetById(filterId);
                    this.DepartmentsCombo = new ObservableCollection<DepartmentDto>() { this.UserDepartment };
                }

                userDepartmentVisible = !this.from1VM;
            }

            if (this.DepartmentsCombo != null && populationMethod.HasFlag(EnumPopulationType.AddNullOrNoneOption))
            {
                this.DepartmentsCombo.Insert(0, this.UserDepartment != null && !this.UserDepartment.IsTransient() ? this.UserDepartment : new DepartmentDto());
            }

            if (populationMethod.HasFlag(EnumPopulationType.OnlyId))
                this.allDepartmentsQueryVM = new DepartmentQueryViewModel(typeof(UserView).FullName);
            else
                this.allDepartmentsQueryVM = new DepartmentQueryViewModel(this.DepartmentsCombo, typeof(UserView).FullName);

            departmentComboVisible = this.DepartmentsCombo.Count() <= 50;
        }


        /// <summary>
        /// example to execute validation rules
        /// </summary>
        /// <param name="validation"></param>
        protected override void SetupValidation(MvvmValidation.ValidationHelper validation)
        {
            //ejemplo de validacion
            //// Validación de hora de Inicio
            //validation.AddRule(
            //                   () => this.propiedad,
            //                   () => RuleResult.Assert(
            //                                           this.propiedad != null,
            //                                           "mensaje"));
        }

        /// <summary>
        /// .en Here is possible to override the actions to execute when there is a navigation request
        /// </summary>
        /// <remarks>
        ///  this logic applys when you came from the collection of users through double click
        ///  load parent entities and populate the related combobox with unique value
        /// .en Here is where to call to the methods to load the related entities (children and parents).
        /// .es aqui es donde se invoca a los métodos de carga de las entidades adicionales.
        /// </remarks>
        public override void OnNavigatedTo(Microsoft.Practices.Prism.Regions.NavigationContext navigationContext)
        {
            base.OnNavigatedTo(navigationContext);
            Int32 parentDepartmentId = default(Int32);

            if (navigationContext.Parameters["Id"] != default(Int32).ToString())//#
            {
                var parameter = navigationContext.Parameters["Id"];
                if (parameter != null)
                {
                    parentDepartmentId = Int32.Parse(parameter.Split(';').Last());
                }
            }

            // populate the combobox
            if (((this.UserDepartment == null && parentDepartmentId == default(Int32)) || (this.UserDepartment != null && this.UserDepartment.Id == default(Int32))) && parentDepartmentId == default(Int32))
            {
                // with all values
                PopulateDepartments(default(Int32), EnumPopulationType.All);
            }
            else
            {
                // only with the parent
                parentDepartmentId = this.UserDepartment != null && this.UserDepartment.Id != default(Int32) ? this.UserDepartment.Id : parentDepartmentId;
                PopulateDepartments(parentDepartmentId, EnumPopulationType.OnlyId ); // get only the parent
            }

            //.en load children entities
            //.es cargar aqui los agregados relacionados

           Initialization(this.ObjectElement);

            if (navigationContext.Parameters["Id"] != default(Int32).ToString())//***
            {
                // only in this case there is a need of subscription to update a parent view
                if (!CompositeViewUpdateEvent.Contains(this.OnReceiveCompositeViewUpdateEvent))
                {
                    CompositeViewUpdateEvent.Subscribe(this.OnReceiveCompositeViewUpdateEvent, ThreadOption.UIThread);
                }
            }

            //AddressServiceClient addressServiceClient = new AddressServiceClient();
            var specDto = new SpecificationDto() { PageIndex = 0, PageSize = 5 };
            specDto.CompositeFilter.Filters.Add(new Filter() { Property = "UserAddress.Id", Operator = "IsEqualTo", Value = navigationContext.Parameters["Id"] });//this.ObjectElement.Id.ToString()
            AddressesQueryVM = new AddressQueryViewModel(specDto, typeof(UserView).FullName);

            //var specDto = new SpecificationDto() { PageIndex = 0, PageSize = 5 };
            //specDto.CompositeFilter.Filters.Add(new Filter() { Property = "Address_Id", Operator = "IsEqualTo", Value = navigationContext.Parameters["Id"] });
            this.AddressesQueryVM = new AddressQueryViewModel(this.ObjectElement.Addresses, this.CurrentViewName);
            this.Address1VM = new AddressViewModel();
            this.AddressesQueryVM.Rebind();
            this.Rebind();
        }

        /// <summary>. en Action to execute when there is a call to update the view.</summary>
        /// <param name="message"></param>
        public override void OnReceiveCompositeViewUpdateEvent(string message)
        {
            this.AddressesQueryVM.OnGetRecords("from UserViewModel");			
        }

        internal void RefreshRelatedEntities()
        {
            this.RaisePropertyChanged(() => this.DepartmentsCombo);
            this.RaisePropertyChanged(() => this.UserDepartment);
        }

        /// <summary>
        /// override of Generic BeginEdit to avoid the edition in the blank line of query viewmodel with double click
        /// </summary>
        public override void BeginEdit()
        {
            if (!this.inTxn && this.IsNotTransient)
            {
                this.inTxn = true;
                if (this.backupEntity == null)
                    this.backupEntity = (UserDto)this.ObjectElement.Clone();
            }
            else
            {
                // this event comes from a double clik in a query view 
                //Dictionary<string, string> parameters = new Dictionary<string, string>();
                //parameters.Add("User; UserDepartment.Id", this.Id.ToString());
                //this.NavigationService.NavigateTo(RegionNames.WorkspaceRegion, typeof(UserView).FullName, parameters);
                this.CancelEdit();
                this.NavigationService.NavigateToWorkSpace(typeof(UserView).FullName, this.Id);
            }
        }
        #endregion
    }
} //  Needel.Common.FrontEnd.WpfModule
