#region Copyright info
//-----------------------------------------------------------------------
// <copyright file="Teacher" company="Company">
//     Copyright (c) 2020. Company. All Rights Reserved.
//     Copyright (c) 2020. Company. Todos los derechos reservados.
//
//     .en This code has been generated by a tool, please don't modify this file or  
//     you will lost all your modifications in the next regeneration.
//      The original t4 template to get this file is " DomainCoreIEntityCT.tt" with "public class DomainCoreIEntityCT : Template"
// 
//     .es Este código ha sido generado por una herramienta, por favor no modifique este fichero
//     o perdera las modificaciones al regenerar este fichero.
//      La plantilla con que se ha generado este fichero es "DomainCoreIEntityCT.tt" con "public class DomainCoreIEntityCT : Template"
//
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace Needel.Common.Domain
{


    #region Usings
    using System;
    using Needel.Common.Domain.Data;
    using Inflexion2.Domain;
    using Inflexion2;
    
    #endregion

    /// <summary>
    /// .en Interfaz to identify an entidad of type Teacher in the application.
    /// .es Interfaz que identifica una entidad de tipo Teacher de la aplicación.
    /// Example for M:N relationships
    /// </summary>
    /// <remarks>
    /// .en Interfaz for an Entity implemented by Teacher/>.
    /// .es Interfaz que representa  una entidad implementado enTeacher/>.
    /// </remarks>
    public interface ITeacher : Inflexion2.Domain.IAggregateRoot<ITeacher, Int32>  , IEquatable<ITeacher>, IComparable<ITeacher>
    {

        #region Properties
        /// <summary>
        /// .en Property to get and set Name.
        /// .es Propiedad que permite obtener y establecer Name.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <value>
        /// .en Value used to get and set Name.
        /// .es Valor que es utilizado para obtener y establecer Name.
        /// </value>
        string Name { get; set; }

        /// <summary>
        /// .en Public property Students.
        /// .es Propiedad pública  Students.
        /// </summary>
        /// <remarks>
        /// .en (SOURCE) This property comes from a relationship  y Asociación
        /// .es (SOURCE)Esta propiedad proviene de una relación de tipo  y Asociación
        /// Nos permite establecer y obtener Students.
        /// </remarks>
        /// <value>
        /// .es Valor que es utilizado para establecer y obtener Students.
        /// </value>
        System.Collections.Generic.List<Student> Students{ get; }
   
        #endregion

        #region Methods

        /// <summary>
        /// .es Método encargado de establecer un nuevo valor para la propiedad Students.
        /// </summary>
        /// <value>
        /// .es Parametro con el que establecemos el nuevo valor de Students.
        /// </value>
        Teacher SetStudents ( System.Collections.Generic.List<Student> students );

        #endregion

    } // End class Teacher.

} // End NameSpace Needel.Common.Domain.
