//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Needel.Common.Application.WcfClient.DepartmentReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DepartmentReference.IDepartmentService")]
    public interface IDepartmentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/Create", ReplyAction="http://tempuri.org/IDepartmentService/CreateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.FaultObject), Action="http://tempuri.org/IDepartmentService/CreateFaultObjectFault", Name="FaultObject", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.ValidationException), Action="http://tempuri.org/IDepartmentService/CreateValidationExceptionFault", Name="ValidationException", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.InternalException), Action="http://tempuri.org/IDepartmentService/CreateInternalExceptionFault", Name="InternalException", Namespace="")]
        int Create(Needel.Common.Application.Dtos.DepartmentDto departmentDto);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDepartmentService/Create", ReplyAction="http://tempuri.org/IDepartmentService/CreateResponse")]
        System.IAsyncResult BeginCreate(Needel.Common.Application.Dtos.DepartmentDto departmentDto, System.AsyncCallback callback, object asyncState);
        
        int EndCreate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/Update", ReplyAction="http://tempuri.org/IDepartmentService/UpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.FaultObject), Action="http://tempuri.org/IDepartmentService/UpdateFaultObjectFault", Name="FaultObject", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.ValidationException), Action="http://tempuri.org/IDepartmentService/UpdateValidationExceptionFault", Name="ValidationException", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.InternalException), Action="http://tempuri.org/IDepartmentService/UpdateInternalExceptionFault", Name="InternalException", Namespace="")]
        bool Update(Needel.Common.Application.Dtos.DepartmentDto departmentDto);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDepartmentService/Update", ReplyAction="http://tempuri.org/IDepartmentService/UpdateResponse")]
        System.IAsyncResult BeginUpdate(Needel.Common.Application.Dtos.DepartmentDto departmentDto, System.AsyncCallback callback, object asyncState);
        
        bool EndUpdate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/Delete", ReplyAction="http://tempuri.org/IDepartmentService/DeleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.FaultObject), Action="http://tempuri.org/IDepartmentService/DeleteFaultObjectFault", Name="FaultObject", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.ValidationException), Action="http://tempuri.org/IDepartmentService/DeleteValidationExceptionFault", Name="ValidationException", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.InternalException), Action="http://tempuri.org/IDepartmentService/DeleteInternalExceptionFault", Name="InternalException", Namespace="")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDepartmentService/Delete", ReplyAction="http://tempuri.org/IDepartmentService/DeleteResponse")]
        System.IAsyncResult BeginDelete(int id, System.AsyncCallback callback, object asyncState);
        
        bool EndDelete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/GetAll", ReplyAction="http://tempuri.org/IDepartmentService/GetAllResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.FaultObject), Action="http://tempuri.org/IDepartmentService/GetAllFaultObjectFault", Name="FaultObject", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.ValidationException), Action="http://tempuri.org/IDepartmentService/GetAllValidationExceptionFault", Name="ValidationException", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.InternalException), Action="http://tempuri.org/IDepartmentService/GetAllInternalExceptionFault", Name="InternalException", Namespace="")]
        System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDepartmentService/GetAll", ReplyAction="http://tempuri.org/IDepartmentService/GetAllResponse")]
        System.IAsyncResult BeginGetAll(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> EndGetAll(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/GetById", ReplyAction="http://tempuri.org/IDepartmentService/GetByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.FaultObject), Action="http://tempuri.org/IDepartmentService/GetByIdFaultObjectFault", Name="FaultObject", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.ValidationException), Action="http://tempuri.org/IDepartmentService/GetByIdValidationExceptionFault", Name="ValidationException", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.InternalException), Action="http://tempuri.org/IDepartmentService/GetByIdInternalExceptionFault", Name="InternalException", Namespace="")]
        Needel.Common.Application.Dtos.DepartmentDto GetById(int departmentId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDepartmentService/GetById", ReplyAction="http://tempuri.org/IDepartmentService/GetByIdResponse")]
        System.IAsyncResult BeginGetById(int departmentId, System.AsyncCallback callback, object asyncState);
        
        Needel.Common.Application.Dtos.DepartmentDto EndGetById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/GetPaged", ReplyAction="http://tempuri.org/IDepartmentService/GetPagedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.FaultObject), Action="http://tempuri.org/IDepartmentService/GetPagedFaultObjectFault", Name="FaultObject", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.ValidationException), Action="http://tempuri.org/IDepartmentService/GetPagedValidationExceptionFault", Name="ValidationException", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.InternalException), Action="http://tempuri.org/IDepartmentService/GetPagedInternalExceptionFault", Name="InternalException", Namespace="")]
        Inflexion2.Domain.PagedElements<Needel.Common.Application.Dtos.DepartmentDto> GetPaged(Inflexion2.Application.SpecificationDto specificationDto);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDepartmentService/GetPaged", ReplyAction="http://tempuri.org/IDepartmentService/GetPagedResponse")]
        System.IAsyncResult BeginGetPaged(Inflexion2.Application.SpecificationDto specificationDto, System.AsyncCallback callback, object asyncState);
        
        Inflexion2.Domain.PagedElements<Needel.Common.Application.Dtos.DepartmentDto> EndGetPaged(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/DeleteAll", ReplyAction="http://tempuri.org/IDepartmentService/DeleteAllResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.FaultObject), Action="http://tempuri.org/IDepartmentService/DeleteAllFaultObjectFault", Name="FaultObject", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.ValidationException), Action="http://tempuri.org/IDepartmentService/DeleteAllValidationExceptionFault", Name="ValidationException", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.InternalException), Action="http://tempuri.org/IDepartmentService/DeleteAllInternalExceptionFault", Name="InternalException", Namespace="")]
        System.Collections.ObjectModel.ObservableCollection<int> DeleteAll();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDepartmentService/DeleteAll", ReplyAction="http://tempuri.org/IDepartmentService/DeleteAllResponse")]
        System.IAsyncResult BeginDeleteAll(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<int> EndDeleteAll(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/GetAllExceptThis", ReplyAction="http://tempuri.org/IDepartmentService/GetAllExceptThisResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.FaultObject), Action="http://tempuri.org/IDepartmentService/GetAllExceptThisFaultObjectFault", Name="FaultObject", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.ValidationException), Action="http://tempuri.org/IDepartmentService/GetAllExceptThisValidationExceptionFault", Name="ValidationException", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.InternalException), Action="http://tempuri.org/IDepartmentService/GetAllExceptThisInternalExceptionFault", Name="InternalException", Namespace="")]
        System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> GetAllExceptThis(int departmentId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDepartmentService/GetAllExceptThis", ReplyAction="http://tempuri.org/IDepartmentService/GetAllExceptThisResponse")]
        System.IAsyncResult BeginGetAllExceptThis(int departmentId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> EndGetAllExceptThis(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/GetSelectedThese", ReplyAction="http://tempuri.org/IDepartmentService/GetSelectedTheseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.FaultObject), Action="http://tempuri.org/IDepartmentService/GetSelectedTheseFaultObjectFault", Name="FaultObject", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.ValidationException), Action="http://tempuri.org/IDepartmentService/GetSelectedTheseValidationExceptionFault", Name="ValidationException", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.InternalException), Action="http://tempuri.org/IDepartmentService/GetSelectedTheseInternalExceptionFault", Name="InternalException", Namespace="")]
        System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> GetSelectedThese(System.Collections.ObjectModel.ObservableCollection<int> departmentIds);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDepartmentService/GetSelectedThese", ReplyAction="http://tempuri.org/IDepartmentService/GetSelectedTheseResponse")]
        System.IAsyncResult BeginGetSelectedThese(System.Collections.ObjectModel.ObservableCollection<int> departmentIds, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> EndGetSelectedThese(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/GetAllExceptThese", ReplyAction="http://tempuri.org/IDepartmentService/GetAllExceptTheseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.FaultObject), Action="http://tempuri.org/IDepartmentService/GetAllExceptTheseFaultObjectFault", Name="FaultObject", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.ValidationException), Action="http://tempuri.org/IDepartmentService/GetAllExceptTheseValidationExceptionFault", Name="ValidationException", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.InternalException), Action="http://tempuri.org/IDepartmentService/GetAllExceptTheseInternalExceptionFault", Name="InternalException", Namespace="")]
        System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> GetAllExceptThese(System.Collections.ObjectModel.ObservableCollection<int> departmentIds);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDepartmentService/GetAllExceptThese", ReplyAction="http://tempuri.org/IDepartmentService/GetAllExceptTheseResponse")]
        System.IAsyncResult BeginGetAllExceptThese(System.Collections.ObjectModel.ObservableCollection<int> departmentIds, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> EndGetAllExceptThese(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/GetFiltered", ReplyAction="http://tempuri.org/IDepartmentService/GetFilteredResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.FaultObject), Action="http://tempuri.org/IDepartmentService/GetFilteredFaultObjectFault", Name="FaultObject", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.ValidationException), Action="http://tempuri.org/IDepartmentService/GetFilteredValidationExceptionFault", Name="ValidationException", Namespace="")]
        [System.ServiceModel.FaultContractAttribute(typeof(Inflexion2.Application.InternalException), Action="http://tempuri.org/IDepartmentService/GetFilteredInternalExceptionFault", Name="InternalException", Namespace="")]
        System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> GetFiltered(Inflexion2.Application.SpecificationDto specificationDto);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDepartmentService/GetFiltered", ReplyAction="http://tempuri.org/IDepartmentService/GetFilteredResponse")]
        System.IAsyncResult BeginGetFiltered(Inflexion2.Application.SpecificationDto specificationDto, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> EndGetFiltered(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDepartmentServiceChannel : Needel.Common.Application.WcfClient.DepartmentReference.IDepartmentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Needel.Common.Application.Dtos.DepartmentDto Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Needel.Common.Application.Dtos.DepartmentDto)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPagedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPagedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Inflexion2.Domain.PagedElements<Needel.Common.Application.Dtos.DepartmentDto> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Inflexion2.Domain.PagedElements<Needel.Common.Application.Dtos.DepartmentDto>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<int> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<int>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllExceptThisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllExceptThisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSelectedTheseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSelectedTheseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllExceptTheseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllExceptTheseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFilteredCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFilteredCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DepartmentServiceClient : System.ServiceModel.ClientBase<Needel.Common.Application.WcfClient.DepartmentReference.IDepartmentService>, Needel.Common.Application.WcfClient.DepartmentReference.IDepartmentService {
        
        private BeginOperationDelegate onBeginCreateDelegate;
        
        private EndOperationDelegate onEndCreateDelegate;
        
        private System.Threading.SendOrPostCallback onCreateCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateDelegate;
        
        private EndOperationDelegate onEndUpdateDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteDelegate;
        
        private EndOperationDelegate onEndDeleteDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllDelegate;
        
        private EndOperationDelegate onEndGetAllDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetByIdDelegate;
        
        private EndOperationDelegate onEndGetByIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetByIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPagedDelegate;
        
        private EndOperationDelegate onEndGetPagedDelegate;
        
        private System.Threading.SendOrPostCallback onGetPagedCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteAllDelegate;
        
        private EndOperationDelegate onEndDeleteAllDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteAllCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllExceptThisDelegate;
        
        private EndOperationDelegate onEndGetAllExceptThisDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllExceptThisCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSelectedTheseDelegate;
        
        private EndOperationDelegate onEndGetSelectedTheseDelegate;
        
        private System.Threading.SendOrPostCallback onGetSelectedTheseCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllExceptTheseDelegate;
        
        private EndOperationDelegate onEndGetAllExceptTheseDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllExceptTheseCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFilteredDelegate;
        
        private EndOperationDelegate onEndGetFilteredDelegate;
        
        private System.Threading.SendOrPostCallback onGetFilteredCompletedDelegate;
        
        public DepartmentServiceClient() {
        }
        
        public DepartmentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DepartmentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartmentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<CreateCompletedEventArgs> CreateCompleted;
        
        public event System.EventHandler<UpdateCompletedEventArgs> UpdateCompleted;
        
        public event System.EventHandler<DeleteCompletedEventArgs> DeleteCompleted;
        
        public event System.EventHandler<GetAllCompletedEventArgs> GetAllCompleted;
        
        public event System.EventHandler<GetByIdCompletedEventArgs> GetByIdCompleted;
        
        public event System.EventHandler<GetPagedCompletedEventArgs> GetPagedCompleted;
        
        public event System.EventHandler<DeleteAllCompletedEventArgs> DeleteAllCompleted;
        
        public event System.EventHandler<GetAllExceptThisCompletedEventArgs> GetAllExceptThisCompleted;
        
        public event System.EventHandler<GetSelectedTheseCompletedEventArgs> GetSelectedTheseCompleted;
        
        public event System.EventHandler<GetAllExceptTheseCompletedEventArgs> GetAllExceptTheseCompleted;
        
        public event System.EventHandler<GetFilteredCompletedEventArgs> GetFilteredCompleted;
        
        public int Create(Needel.Common.Application.Dtos.DepartmentDto departmentDto) {
            return base.Channel.Create(departmentDto);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCreate(Needel.Common.Application.Dtos.DepartmentDto departmentDto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreate(departmentDto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndCreate(System.IAsyncResult result) {
            return base.Channel.EndCreate(result);
        }
        
        private System.IAsyncResult OnBeginCreate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Needel.Common.Application.Dtos.DepartmentDto departmentDto = ((Needel.Common.Application.Dtos.DepartmentDto)(inValues[0]));
            return this.BeginCreate(departmentDto, callback, asyncState);
        }
        
        private object[] OnEndCreate(System.IAsyncResult result) {
            int retVal = this.EndCreate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateCompleted(object state) {
            if ((this.CreateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateCompleted(this, new CreateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateAsync(Needel.Common.Application.Dtos.DepartmentDto departmentDto) {
            this.CreateAsync(departmentDto, null);
        }
        
        public void CreateAsync(Needel.Common.Application.Dtos.DepartmentDto departmentDto, object userState) {
            if ((this.onBeginCreateDelegate == null)) {
                this.onBeginCreateDelegate = new BeginOperationDelegate(this.OnBeginCreate);
            }
            if ((this.onEndCreateDelegate == null)) {
                this.onEndCreateDelegate = new EndOperationDelegate(this.OnEndCreate);
            }
            if ((this.onCreateCompletedDelegate == null)) {
                this.onCreateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateCompleted);
            }
            base.InvokeAsync(this.onBeginCreateDelegate, new object[] {
                        departmentDto}, this.onEndCreateDelegate, this.onCreateCompletedDelegate, userState);
        }
        
        public bool Update(Needel.Common.Application.Dtos.DepartmentDto departmentDto) {
            return base.Channel.Update(departmentDto);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUpdate(Needel.Common.Application.Dtos.DepartmentDto departmentDto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdate(departmentDto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndUpdate(System.IAsyncResult result) {
            return base.Channel.EndUpdate(result);
        }
        
        private System.IAsyncResult OnBeginUpdate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Needel.Common.Application.Dtos.DepartmentDto departmentDto = ((Needel.Common.Application.Dtos.DepartmentDto)(inValues[0]));
            return this.BeginUpdate(departmentDto, callback, asyncState);
        }
        
        private object[] OnEndUpdate(System.IAsyncResult result) {
            bool retVal = this.EndUpdate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateCompleted(object state) {
            if ((this.UpdateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateAsync(Needel.Common.Application.Dtos.DepartmentDto departmentDto) {
            this.UpdateAsync(departmentDto, null);
        }
        
        public void UpdateAsync(Needel.Common.Application.Dtos.DepartmentDto departmentDto, object userState) {
            if ((this.onBeginUpdateDelegate == null)) {
                this.onBeginUpdateDelegate = new BeginOperationDelegate(this.OnBeginUpdate);
            }
            if ((this.onEndUpdateDelegate == null)) {
                this.onEndUpdateDelegate = new EndOperationDelegate(this.OnEndUpdate);
            }
            if ((this.onUpdateCompletedDelegate == null)) {
                this.onUpdateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateDelegate, new object[] {
                        departmentDto}, this.onEndUpdateDelegate, this.onUpdateCompletedDelegate, userState);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDelete(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDelete(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndDelete(System.IAsyncResult result) {
            return base.Channel.EndDelete(result);
        }
        
        private System.IAsyncResult OnBeginDelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return this.BeginDelete(id, callback, asyncState);
        }
        
        private object[] OnEndDelete(System.IAsyncResult result) {
            bool retVal = this.EndDelete(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteCompleted(object state) {
            if ((this.DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteAsync(int id) {
            this.DeleteAsync(id, null);
        }
        
        public void DeleteAsync(int id, object userState) {
            if ((this.onBeginDeleteDelegate == null)) {
                this.onBeginDeleteDelegate = new BeginOperationDelegate(this.OnBeginDelete);
            }
            if ((this.onEndDeleteDelegate == null)) {
                this.onEndDeleteDelegate = new EndOperationDelegate(this.OnEndDelete);
            }
            if ((this.onDeleteCompletedDelegate == null)) {
                this.onDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteDelegate, new object[] {
                        id}, this.onEndDeleteDelegate, this.onDeleteCompletedDelegate, userState);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> GetAll() {
            return base.Channel.GetAll();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAll(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAll(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> EndGetAll(System.IAsyncResult result) {
            return base.Channel.EndGetAll(result);
        }
        
        private System.IAsyncResult OnBeginGetAll(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetAll(callback, asyncState);
        }
        
        private object[] OnEndGetAll(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> retVal = this.EndGetAll(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllCompleted(object state) {
            if ((this.GetAllCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllCompleted(this, new GetAllCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllAsync() {
            this.GetAllAsync(null);
        }
        
        public void GetAllAsync(object userState) {
            if ((this.onBeginGetAllDelegate == null)) {
                this.onBeginGetAllDelegate = new BeginOperationDelegate(this.OnBeginGetAll);
            }
            if ((this.onEndGetAllDelegate == null)) {
                this.onEndGetAllDelegate = new EndOperationDelegate(this.OnEndGetAll);
            }
            if ((this.onGetAllCompletedDelegate == null)) {
                this.onGetAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllDelegate, null, this.onEndGetAllDelegate, this.onGetAllCompletedDelegate, userState);
        }
        
        public Needel.Common.Application.Dtos.DepartmentDto GetById(int departmentId) {
            return base.Channel.GetById(departmentId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetById(int departmentId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetById(departmentId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Needel.Common.Application.Dtos.DepartmentDto EndGetById(System.IAsyncResult result) {
            return base.Channel.EndGetById(result);
        }
        
        private System.IAsyncResult OnBeginGetById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int departmentId = ((int)(inValues[0]));
            return this.BeginGetById(departmentId, callback, asyncState);
        }
        
        private object[] OnEndGetById(System.IAsyncResult result) {
            Needel.Common.Application.Dtos.DepartmentDto retVal = this.EndGetById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetByIdCompleted(object state) {
            if ((this.GetByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetByIdCompleted(this, new GetByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetByIdAsync(int departmentId) {
            this.GetByIdAsync(departmentId, null);
        }
        
        public void GetByIdAsync(int departmentId, object userState) {
            if ((this.onBeginGetByIdDelegate == null)) {
                this.onBeginGetByIdDelegate = new BeginOperationDelegate(this.OnBeginGetById);
            }
            if ((this.onEndGetByIdDelegate == null)) {
                this.onEndGetByIdDelegate = new EndOperationDelegate(this.OnEndGetById);
            }
            if ((this.onGetByIdCompletedDelegate == null)) {
                this.onGetByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetByIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetByIdDelegate, new object[] {
                        departmentId}, this.onEndGetByIdDelegate, this.onGetByIdCompletedDelegate, userState);
        }
        
        public Inflexion2.Domain.PagedElements<Needel.Common.Application.Dtos.DepartmentDto> GetPaged(Inflexion2.Application.SpecificationDto specificationDto) {
            return base.Channel.GetPaged(specificationDto);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetPaged(Inflexion2.Application.SpecificationDto specificationDto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPaged(specificationDto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Inflexion2.Domain.PagedElements<Needel.Common.Application.Dtos.DepartmentDto> EndGetPaged(System.IAsyncResult result) {
            return base.Channel.EndGetPaged(result);
        }
        
        private System.IAsyncResult OnBeginGetPaged(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Inflexion2.Application.SpecificationDto specificationDto = ((Inflexion2.Application.SpecificationDto)(inValues[0]));
            return this.BeginGetPaged(specificationDto, callback, asyncState);
        }
        
        private object[] OnEndGetPaged(System.IAsyncResult result) {
            Inflexion2.Domain.PagedElements<Needel.Common.Application.Dtos.DepartmentDto> retVal = this.EndGetPaged(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPagedCompleted(object state) {
            if ((this.GetPagedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPagedCompleted(this, new GetPagedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPagedAsync(Inflexion2.Application.SpecificationDto specificationDto) {
            this.GetPagedAsync(specificationDto, null);
        }
        
        public void GetPagedAsync(Inflexion2.Application.SpecificationDto specificationDto, object userState) {
            if ((this.onBeginGetPagedDelegate == null)) {
                this.onBeginGetPagedDelegate = new BeginOperationDelegate(this.OnBeginGetPaged);
            }
            if ((this.onEndGetPagedDelegate == null)) {
                this.onEndGetPagedDelegate = new EndOperationDelegate(this.OnEndGetPaged);
            }
            if ((this.onGetPagedCompletedDelegate == null)) {
                this.onGetPagedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPagedCompleted);
            }
            base.InvokeAsync(this.onBeginGetPagedDelegate, new object[] {
                        specificationDto}, this.onEndGetPagedDelegate, this.onGetPagedCompletedDelegate, userState);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<int> DeleteAll() {
            return base.Channel.DeleteAll();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDeleteAll(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteAll(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.ObjectModel.ObservableCollection<int> EndDeleteAll(System.IAsyncResult result) {
            return base.Channel.EndDeleteAll(result);
        }
        
        private System.IAsyncResult OnBeginDeleteAll(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginDeleteAll(callback, asyncState);
        }
        
        private object[] OnEndDeleteAll(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<int> retVal = this.EndDeleteAll(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteAllCompleted(object state) {
            if ((this.DeleteAllCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteAllCompleted(this, new DeleteAllCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteAllAsync() {
            this.DeleteAllAsync(null);
        }
        
        public void DeleteAllAsync(object userState) {
            if ((this.onBeginDeleteAllDelegate == null)) {
                this.onBeginDeleteAllDelegate = new BeginOperationDelegate(this.OnBeginDeleteAll);
            }
            if ((this.onEndDeleteAllDelegate == null)) {
                this.onEndDeleteAllDelegate = new EndOperationDelegate(this.OnEndDeleteAll);
            }
            if ((this.onDeleteAllCompletedDelegate == null)) {
                this.onDeleteAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteAllCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteAllDelegate, null, this.onEndDeleteAllDelegate, this.onDeleteAllCompletedDelegate, userState);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> GetAllExceptThis(int departmentId) {
            return base.Channel.GetAllExceptThis(departmentId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAllExceptThis(int departmentId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllExceptThis(departmentId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> EndGetAllExceptThis(System.IAsyncResult result) {
            return base.Channel.EndGetAllExceptThis(result);
        }
        
        private System.IAsyncResult OnBeginGetAllExceptThis(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int departmentId = ((int)(inValues[0]));
            return this.BeginGetAllExceptThis(departmentId, callback, asyncState);
        }
        
        private object[] OnEndGetAllExceptThis(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> retVal = this.EndGetAllExceptThis(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllExceptThisCompleted(object state) {
            if ((this.GetAllExceptThisCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllExceptThisCompleted(this, new GetAllExceptThisCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllExceptThisAsync(int departmentId) {
            this.GetAllExceptThisAsync(departmentId, null);
        }
        
        public void GetAllExceptThisAsync(int departmentId, object userState) {
            if ((this.onBeginGetAllExceptThisDelegate == null)) {
                this.onBeginGetAllExceptThisDelegate = new BeginOperationDelegate(this.OnBeginGetAllExceptThis);
            }
            if ((this.onEndGetAllExceptThisDelegate == null)) {
                this.onEndGetAllExceptThisDelegate = new EndOperationDelegate(this.OnEndGetAllExceptThis);
            }
            if ((this.onGetAllExceptThisCompletedDelegate == null)) {
                this.onGetAllExceptThisCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllExceptThisCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllExceptThisDelegate, new object[] {
                        departmentId}, this.onEndGetAllExceptThisDelegate, this.onGetAllExceptThisCompletedDelegate, userState);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> GetSelectedThese(System.Collections.ObjectModel.ObservableCollection<int> departmentIds) {
            return base.Channel.GetSelectedThese(departmentIds);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetSelectedThese(System.Collections.ObjectModel.ObservableCollection<int> departmentIds, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSelectedThese(departmentIds, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> EndGetSelectedThese(System.IAsyncResult result) {
            return base.Channel.EndGetSelectedThese(result);
        }
        
        private System.IAsyncResult OnBeginGetSelectedThese(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.ObjectModel.ObservableCollection<int> departmentIds = ((System.Collections.ObjectModel.ObservableCollection<int>)(inValues[0]));
            return this.BeginGetSelectedThese(departmentIds, callback, asyncState);
        }
        
        private object[] OnEndGetSelectedThese(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> retVal = this.EndGetSelectedThese(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSelectedTheseCompleted(object state) {
            if ((this.GetSelectedTheseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSelectedTheseCompleted(this, new GetSelectedTheseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSelectedTheseAsync(System.Collections.ObjectModel.ObservableCollection<int> departmentIds) {
            this.GetSelectedTheseAsync(departmentIds, null);
        }
        
        public void GetSelectedTheseAsync(System.Collections.ObjectModel.ObservableCollection<int> departmentIds, object userState) {
            if ((this.onBeginGetSelectedTheseDelegate == null)) {
                this.onBeginGetSelectedTheseDelegate = new BeginOperationDelegate(this.OnBeginGetSelectedThese);
            }
            if ((this.onEndGetSelectedTheseDelegate == null)) {
                this.onEndGetSelectedTheseDelegate = new EndOperationDelegate(this.OnEndGetSelectedThese);
            }
            if ((this.onGetSelectedTheseCompletedDelegate == null)) {
                this.onGetSelectedTheseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSelectedTheseCompleted);
            }
            base.InvokeAsync(this.onBeginGetSelectedTheseDelegate, new object[] {
                        departmentIds}, this.onEndGetSelectedTheseDelegate, this.onGetSelectedTheseCompletedDelegate, userState);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> GetAllExceptThese(System.Collections.ObjectModel.ObservableCollection<int> departmentIds) {
            return base.Channel.GetAllExceptThese(departmentIds);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAllExceptThese(System.Collections.ObjectModel.ObservableCollection<int> departmentIds, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllExceptThese(departmentIds, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> EndGetAllExceptThese(System.IAsyncResult result) {
            return base.Channel.EndGetAllExceptThese(result);
        }
        
        private System.IAsyncResult OnBeginGetAllExceptThese(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.ObjectModel.ObservableCollection<int> departmentIds = ((System.Collections.ObjectModel.ObservableCollection<int>)(inValues[0]));
            return this.BeginGetAllExceptThese(departmentIds, callback, asyncState);
        }
        
        private object[] OnEndGetAllExceptThese(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> retVal = this.EndGetAllExceptThese(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllExceptTheseCompleted(object state) {
            if ((this.GetAllExceptTheseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllExceptTheseCompleted(this, new GetAllExceptTheseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllExceptTheseAsync(System.Collections.ObjectModel.ObservableCollection<int> departmentIds) {
            this.GetAllExceptTheseAsync(departmentIds, null);
        }
        
        public void GetAllExceptTheseAsync(System.Collections.ObjectModel.ObservableCollection<int> departmentIds, object userState) {
            if ((this.onBeginGetAllExceptTheseDelegate == null)) {
                this.onBeginGetAllExceptTheseDelegate = new BeginOperationDelegate(this.OnBeginGetAllExceptThese);
            }
            if ((this.onEndGetAllExceptTheseDelegate == null)) {
                this.onEndGetAllExceptTheseDelegate = new EndOperationDelegate(this.OnEndGetAllExceptThese);
            }
            if ((this.onGetAllExceptTheseCompletedDelegate == null)) {
                this.onGetAllExceptTheseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllExceptTheseCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllExceptTheseDelegate, new object[] {
                        departmentIds}, this.onEndGetAllExceptTheseDelegate, this.onGetAllExceptTheseCompletedDelegate, userState);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> GetFiltered(Inflexion2.Application.SpecificationDto specificationDto) {
            return base.Channel.GetFiltered(specificationDto);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetFiltered(Inflexion2.Application.SpecificationDto specificationDto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFiltered(specificationDto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> EndGetFiltered(System.IAsyncResult result) {
            return base.Channel.EndGetFiltered(result);
        }
        
        private System.IAsyncResult OnBeginGetFiltered(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Inflexion2.Application.SpecificationDto specificationDto = ((Inflexion2.Application.SpecificationDto)(inValues[0]));
            return this.BeginGetFiltered(specificationDto, callback, asyncState);
        }
        
        private object[] OnEndGetFiltered(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Needel.Common.Application.Dtos.DepartmentDto> retVal = this.EndGetFiltered(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFilteredCompleted(object state) {
            if ((this.GetFilteredCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFilteredCompleted(this, new GetFilteredCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFilteredAsync(Inflexion2.Application.SpecificationDto specificationDto) {
            this.GetFilteredAsync(specificationDto, null);
        }
        
        public void GetFilteredAsync(Inflexion2.Application.SpecificationDto specificationDto, object userState) {
            if ((this.onBeginGetFilteredDelegate == null)) {
                this.onBeginGetFilteredDelegate = new BeginOperationDelegate(this.OnBeginGetFiltered);
            }
            if ((this.onEndGetFilteredDelegate == null)) {
                this.onEndGetFilteredDelegate = new EndOperationDelegate(this.OnEndGetFiltered);
            }
            if ((this.onGetFilteredCompletedDelegate == null)) {
                this.onGetFilteredCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFilteredCompleted);
            }
            base.InvokeAsync(this.onBeginGetFilteredDelegate, new object[] {
                        specificationDto}, this.onEndGetFilteredDelegate, this.onGetFilteredCompletedDelegate, userState);
        }
    }
}
