#region Copyright info
//-----------------------------------------------------------------------
// <copyright file="Department" company="Company">
//     Copyright (c) 2020. Company. All Rights Reserved.
//     Copyright (c) 2020. Company. Todos los derechos reservados.
//
//     .en This code has been generated by a tool, please don't modify this file or  
//     you will lost all your modifications in the next regeneration.
//      The original t4 template to get this file is " ApplicationEntityDtoCT.tt" with "public class ApplicationEntityDtoCT : Template"
// 
//     .es Este código ha sido generado por una herramienta, por favor no modifique este fichero
//     o perdera las modificaciones al regenerar este fichero.
//      La plantilla con que se ha generado este fichero es "ApplicationEntityDtoCT.tt" con "public class ApplicationEntityDtoCT : Template"
//
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace Needel.Common.Application.Dtos
{

    #region SharedKernel usings
    #endregion

    #region usings
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Inflexion2.Application;//.DataTransfer.Base;

    using Needel.Common.Domain.Data;

    using System.Collections.ObjectModel;
    #endregion

    /// <summary>
    /// Clase que representa a la entidad <see cref="DepartmentDto"/>.
    /// </summary>
    /// <remarks>
    /// Crea un objeto <see cref="DepartmentDto"/>.
    /// </remarks>
    // no tiene subclases
    // no tiene superclases
    [DataContract]
    public  class DepartmentDto : BaseEntityDataTransferObject<Int32> 
    {
        #region CONSTRUCTORS
        
        /// <summary>
        /// Inicializa una nueva instancia de la clase <see cref="DepartmentDto"/>.
        /// </summary>
        /// <remarks>
        /// Constructor de la clase <see cref="DepartmentDto"/>.
        /// </remarks>
        public DepartmentDto()
        {
            this.Users = new System.Collections.Generic.List<UserDto>();
        } // DepartmentDto Constructor

        #endregion

        #region PROPERTIES

        /// <summary>
        /// Variable privada que identifica Name.
        /// </summary>
        /// <remarks>
        /// Name of the department.
        /// </remarks>
        [DataMember]
        public string Name {get; set;}

        /// <summary>
        /// Variable privada que identifica Visible.
        /// </summary>
        /// <remarks>
        /// visibility mark
        /// </remarks>
        [DataMember]
        public bool Visible {get; set;}

        /// <summary>
        /// Variable privada que identifica Description.
        /// </summary>
        /// <remarks>
        /// Allow to the user to explain what is the responsabilities or functions of the department.
        /// </remarks>
        [DataMember]
        public string Description {get; set;}

        /// <summary>
        /// Variable privada que identifica CreationTime.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public DateTime CreationTime {get; set;}

        /// <summary>
        /// Variable privada que identifica UpdateTime.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        [DataMember]
        public DateTime? UpdateTime {get; set;}

        /// <summary>
        /// Campo privado para almacenar la colección de  Users.
        /// </summary>
        /// <remarks>
        /// Nos permite establecer y obtener Users.
        /// Propiedad proveniente del rol target de una relación.
        /// </remarks>
        [DataMember]
        public System.Collections.Generic.List<UserDto> Users {get; set;}/*from targets*/
        #endregion

        #region Actual IClonable implementation

        /// <summary>
        /// Actual IClonable implementation to help the IEditableObject Implementation 
        /// </summary>
        /// <returns></returns>
        public override object Clone()
        {
            var obj = new DepartmentDto();
            obj.Id = this.Id;
            obj.Name = this.Name;
            obj.Visible = this.Visible;
            obj.Description = this.Description;
            obj.CreationTime = this.CreationTime;
            obj.UpdateTime = this.UpdateTime;

            //Parents from sources

            //Children from targets
            if (this.Users != null && this.Users.Count > 0)
            {
                obj.Users = new System.Collections.Generic.List<UserDto>();
                foreach (var item in this.Users)
                {
                    obj.Users.Add((UserDto)item.Clone());
                }                
            }

            return obj;
        }
        #endregion

    } // end class DepartmentDto
} //  Needel.Common.Application.Dtos

