//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Needel.Common.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Needel.Common.Infrastructure.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ActualizarEsquemaProduct {
            get {
                return ResourceManager.GetString("ActualizarEsquemaProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Number.
        /// </summary>
        public static string Address_BuildingNumberAlias {
            get {
                return ResourceManager.GetString("Address_BuildingNumberAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Number.
        /// </summary>
        public static string Address_BuildingNumberTooltip {
            get {
                return ResourceManager.GetString("Address_BuildingNumberTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Number.
        /// </summary>
        public static string Address_BuildingNumberUserRemarks {
            get {
                return ResourceManager.GetString("Address_BuildingNumberUserRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name.
        /// </summary>
        public static string Address_StreetNameAlias {
            get {
                return ResourceManager.GetString("Address_StreetNameAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name.
        /// </summary>
        public static string Address_StreetNameTooltip {
            get {
                return ResourceManager.GetString("Address_StreetNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name.
        /// </summary>
        public static string Address_StreetNameUserRemarks {
            get {
                return ResourceManager.GetString("Address_StreetNameUserRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AddressAlias {
            get {
                return ResourceManager.GetString("AddressAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string AddressPluralEntity {
            get {
                return ResourceManager.GetString("AddressPluralEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AddressRemarks {
            get {
                return ResourceManager.GetString("AddressRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AddressTooltip {
            get {
                return ResourceManager.GetString("AddressTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AñadirDatosMaquetaProduct {
            get {
                return ResourceManager.GetString("AñadirDatosMaquetaProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Setting Using.
        /// </summary>
        public static string AppSetting_AppSettingUsingAlias_ {
            get {
                return ResourceManager.GetString("AppSetting_AppSettingUsingAlias_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string AppSetting_KeyAlias {
            get {
                return ResourceManager.GetString("AppSetting_KeyAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App setting key.
        /// </summary>
        public static string AppSetting_KeyTooltip {
            get {
                return ResourceManager.GetString("AppSetting_KeyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a preference usually managed by the programmers to modify the behavieur of the application for all or only some users..
        /// </summary>
        public static string AppSetting_KeyUserRemarks {
            get {
                return ResourceManager.GetString("AppSetting_KeyUserRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string AppSetting_RemarkAlias {
            get {
                return ResourceManager.GetString("AppSetting_RemarkAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key value par description..
        /// </summary>
        public static string AppSetting_RemarkTooltip {
            get {
                return ResourceManager.GetString("AppSetting_RemarkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please introduce herer how to use this settings or what is his meaning..
        /// </summary>
        public static string AppSetting_RemarkUserRemarks {
            get {
                return ResourceManager.GetString("AppSetting_RemarkUserRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string AppSetting_ValueAlias {
            get {
                return ResourceManager.GetString("AppSetting_ValueAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string AppSetting_ValueTooltip {
            get {
                return ResourceManager.GetString("AppSetting_ValueTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string AppSetting_ValueUserRemarks {
            get {
                return ResourceManager.GetString("AppSetting_ValueUserRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Setting.
        /// </summary>
        public static string AppSettingAlias {
            get {
                return ResourceManager.GetString("AppSettingAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        public static string AppSettingPluralEntity {
            get {
                return ResourceManager.GetString("AppSettingPluralEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings to manage diferent options..
        /// </summary>
        public static string AppSettingRemarks {
            get {
                return ResourceManager.GetString("AppSettingRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings and user Options.
        /// </summary>
        public static string AppSettingTooltip {
            get {
                return ResourceManager.GetString("AppSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Setting Type.
        /// </summary>
        public static string AppSettingTypeAlias {
            get {
                return ResourceManager.GetString("AppSettingTypeAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSettingTypes.
        /// </summary>
        public static string AppSettingTypePluralEntity {
            get {
                return ResourceManager.GetString("AppSettingTypePluralEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration user remarks.
        /// </summary>
        public static string AppSettingTypeRemarks {
            get {
                return ResourceManager.GetString("AppSettingTypeRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Setting Type.
        /// </summary>
        public static string AppSettingTypeTooltip {
            get {
                return ResourceManager.GetString("AppSettingTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ar).
        /// </summary>
        public static string ar {
            get {
                return ResourceManager.GetString("ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Ayuda {
            get {
                return ResourceManager.GetString("Ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BorrarDatosMaquetaProduct {
            get {
                return ResourceManager.GetString("BorrarDatosMaquetaProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BorraryCrearEsquemaProduct {
            get {
                return ResourceManager.GetString("BorraryCrearEsquemaProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BureauBlack.
        /// </summary>
        public static string BureauBlack {
            get {
                return ResourceManager.GetString("BureauBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BureauBlue.
        /// </summary>
        public static string BureauBlue {
            get {
                return ResourceManager.GetString("BureauBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContextoLimitado {
            get {
                return ResourceManager.GetString("ContextoLimitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string contraseña {
            get {
                return ResourceManager.GetString("contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (de).
        /// </summary>
        public static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time.
        /// </summary>
        public static string Department_CreationTimeAlias {
            get {
                return ResourceManager.GetString("Department_CreationTimeAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time.
        /// </summary>
        public static string Department_CreationTimeTooltip {
            get {
                return ResourceManager.GetString("Department_CreationTimeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time.
        /// </summary>
        public static string Department_CreationTimeUserRemarks {
            get {
                return ResourceManager.GetString("Department_CreationTimeUserRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Department_DescriptionAlias {
            get {
                return ResourceManager.GetString("Department_DescriptionAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department&apos;s description..
        /// </summary>
        public static string Department_DescriptionTooltip {
            get {
                return ResourceManager.GetString("Department_DescriptionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please explain here what are the main responsabilities or functions of this department..
        /// </summary>
        public static string Department_DescriptionUserRemarks {
            get {
                return ResourceManager.GetString("Department_DescriptionUserRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Department_NameAlias {
            get {
                return ResourceManager.GetString("Department_NameAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department&apos;s name..
        /// </summary>
        public static string Department_NameTooltip {
            get {
                return ResourceManager.GetString("Department_NameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please introduce here the name o identifcation of the department..
        /// </summary>
        public static string Department_NameUserRemarks {
            get {
                return ResourceManager.GetString("Department_NameUserRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Time.
        /// </summary>
        public static string Department_UpdateTimeAlias {
            get {
                return ResourceManager.GetString("Department_UpdateTimeAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Time.
        /// </summary>
        public static string Department_UpdateTimeTooltip {
            get {
                return ResourceManager.GetString("Department_UpdateTimeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Time.
        /// </summary>
        public static string Department_UpdateTimeUserRemarks {
            get {
                return ResourceManager.GetString("Department_UpdateTimeUserRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Department_UsersAlias__ {
            get {
                return ResourceManager.GetString("Department_UsersAlias__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string Department_VisibleAlias {
            get {
                return ResourceManager.GetString("Department_VisibleAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow the visibility/activation of this department..
        /// </summary>
        public static string Department_VisibleTooltip {
            get {
                return ResourceManager.GetString("Department_VisibleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use this field to deactivate/activate this deparment..
        /// </summary>
        public static string Department_VisibleUserRemarks {
            get {
                return ResourceManager.GetString("Department_VisibleUserRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DepartmentAlias {
            get {
                return ResourceManager.GetString("DepartmentAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string DepartmentPluralEntity {
            get {
                return ResourceManager.GetString("DepartmentPluralEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Depatment organigram.
        /// </summary>
        public static string DepartmentRemarks {
            get {
                return ResourceManager.GetString("DepartmentRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department basic structure.
        /// </summary>
        public static string DepartmentTooltip {
            get {
                return ResourceManager.GetString("DepartmentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Elobjetodeestaaplicacióneselde {
            get {
                return ResourceManager.GetString("Elobjetodeestaaplicacióneselde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (en).
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (es).
        /// </summary>
        public static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpressionDark.
        /// </summary>
        public static string ExpressionDark {
            get {
                return ResourceManager.GetString("ExpressionDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpressionLight.
        /// </summary>
        public static string ExpressionLight {
            get {
                return ResourceManager.GetString("ExpressionLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External User.
        /// </summary>
        public static string ExternalUser {
            get {
                return ResourceManager.GetString("ExternalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string flow {
            get {
                return ResourceManager.GetString("flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (fr).
        /// </summary>
        public static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GestordeEsquemasdeBD {
            get {
                return ResourceManager.GetString("GestordeEsquemasdeBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (he).
        /// </summary>
        public static string he {
            get {
                return ResourceManager.GetString("he", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew.
        /// </summary>
        public static string Hebrew {
            get {
                return ResourceManager.GetString("Hebrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal User.
        /// </summary>
        public static string InternalUser {
            get {
                return ResourceManager.GetString("InternalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (it).
        /// </summary>
        public static string it {
            get {
                return ResourceManager.GetString("it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ja).
        /// </summary>
        public static string ja {
            get {
                return ResourceManager.GetString("ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsSql2008 {
            get {
                return ResourceManager.GetString("MsSql2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NH3BeginnersGuide {
            get {
                return ResourceManager.GetString("NH3BeginnersGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Nombredelabasededatos {
            get {
                return ResourceManager.GetString("Nombredelabasededatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Nombredelservidor {
            get {
                return ResourceManager.GetString("Nombredelservidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NombreDeUsuario {
            get {
                return ResourceManager.GetString("NombreDeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (pt).
        /// </summary>
        public static string pt {
            get {
                return ResourceManager.GetString("pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string QUAD {
            get {
                return ResourceManager.GetString("QUAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ScriptActualización {
            get {
                return ResourceManager.GetString("ScriptActualización", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ScriptCreación {
            get {
                return ResourceManager.GetString("ScriptCreación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ScriptSqlBorraryCrearEsquemaPr {
            get {
                return ResourceManager.GetString("ScriptSqlBorraryCrearEsquemaPr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SelectTheme {
            get {
                return ResourceManager.GetString("SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShinyBlue.
        /// </summary>
        public static string ShinyBlue {
            get {
                return ResourceManager.GetString("ShinyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShinyRed.
        /// </summary>
        public static string ShinyRed {
            get {
                return ResourceManager.GetString("ShinyRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SistemaOperativo {
            get {
                return ResourceManager.GetString("SistemaOperativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Tecnologíadelabasededatos {
            get {
                return ResourceManager.GetString("Tecnologíadelabasededatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string User_AddressesAlias__ {
            get {
                return ResourceManager.GetString("User_AddressesAlias__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string User_DepartmentAlias_ {
            get {
                return ResourceManager.GetString("User_DepartmentAlias_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property&apos;Name&apos; of the entity &apos;User&apos; has a minimun lenght of and a maximum lenght of &apos;.
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string User_NameAlias {
            get {
                return ResourceManager.GetString("User_NameAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field explanation..
        /// </summary>
        public static string User_NameTooltip {
            get {
                return ResourceManager.GetString("User_NameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please explain here what is the meanig of this field..
        /// </summary>
        public static string User_NameUserRemarks {
            get {
                return ResourceManager.GetString("User_NameUserRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserAlias {
            get {
                return ResourceManager.GetString("UserAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UserPluralEntity {
            get {
                return ResourceManager.GetString("UserPluralEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information data.
        /// </summary>
        public static string UserRemarks {
            get {
                return ResourceManager.GetString("UserRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User base information (internal, externals).
        /// </summary>
        public static string UserTooltip {
            get {
                return ResourceManager.GetString("UserTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhistlerBlue.
        /// </summary>
        public static string WhistlerBlue {
            get {
                return ResourceManager.GetString("WhistlerBlue", resourceCulture);
            }
        }
    }
}
