
#region Copyright info
//-----------------------------------------------------------------------
// <copyright file="User" company="Company">
//     Copyright (c) 2020. Company. All Rights Reserved.
//     Copyright (c) 2020. Company. Todos los derechos reservados.
//
//     .en This code has been generated by a tool, please don't modify this file or  
//     you will lost all your modifications in the next regeneration.
//      The original t4 template to get this file is " CreateSQLServerDataBaseTest.tt" with "public class CreateSQLServerDataBaseTest : Template"
// 
//     .es Este código ha sido generado por una herramienta, por favor no modifique este fichero
//     o perdera las modificaciones al regenerar este fichero.
//      La plantilla con que se ha generado este fichero es "CreateSQLServerDataBaseTest.tt" con "public class CreateSQLServerDataBaseTest : Template"
//
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace Needel.Common.Test.InfrastructureLayer
{

    #region usings
    using System;
    using System.Text;
    using System.Collections.Generic;
    using System.Linq;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using System.Data.Entity;
    using Microsoft.Practices.Unity;
    using Inflexion2.Domain;
    using Inflexion2;
    using Inflexion2.Infrastructure;
    using Inflexion2.Data;
    using Inflexion2.Security;
    using System.Configuration;

    using Needel.Common.Domain.Data;
    using Needel.Common.Domain;
    using Needel.Common.Infrastructure;
    #endregion

    /// <summary>
    /// test de creación de la base de datos para sqlserver
    /// </summary>
    [TestClass]
    public class CommonCreateDaBase 
    {
        Needel.Common.Domain.PerLifeTimeManager unitOfWorkPerTestLifeTimeManager = new Needel.Common.Domain.PerLifeTimeManager();
        Needel.Common.Domain.PerLifeTimeManager contextPerTestLifeTimeManager = new PerLifeTimeManager();
        Microsoft.Practices.Unity.UnityContainer unityContainer;
        string connString = null;

        /// <summary>
        /// use this test to create the database
        /// </summary>
        [TestMethod]
        public void DataBaseCreateTest()
        {
            //this.unityContainer = new UnityContainer();

            //ServiceLocator.Initialize(
            //    (x, y) => this.unityContainer.RegisterType(x, y),
            //    (x, y) => this.unityContainer.RegisterInstance(x, y),
            //    (x) => { return this.unityContainer.Resolve(x); },
            //    (x) => { return this.unityContainer.ResolveAll(x); });

            // Context Factory
            connString = this.ConnectionString();
            EfUnitOfWorkFactory<Needel.Common.Infrastructure.BootstrapUnitOfWork> ctxFactory = new EfUnitOfWorkFactory<BootstrapUnitOfWork>(connString);

            if (!ctxFactory.DatabaseExists())
            {
                ctxFactory.CreateDatabase();
            }
            Assert.AreEqual(true, ctxFactory.DatabaseExists());
        }// end data base create

        #region Common Methods
        /// <summary>
        /// method to get the conection string and create the database
        /// </summary>
        protected virtual string ConnectionString()
        {
            return System.Configuration.ConfigurationManager.ConnectionStrings["Needel.Connection"].ConnectionString;
        }
        
        /// <summary>
        /// commit adapter for the UoW of the current ORM
        /// </summary>
        public void Commit()
        {
            IUnitOfWork unitOfWork = this.unityContainer.Resolve<IUnitOfWork>();
            unitOfWork.Commit();
        }
        #endregion
    }



} //  Needel.Common.Test.InfrastructureLayer
