#region Copyright info
//-----------------------------------------------------------------------
// <copyright file="MNZ" company="Company">
//     Copyright (c) 2020. Company. All Rights Reserved.
//     Copyright (c) 2020. Company. Todos los derechos reservados.
//
//     .en This code has been generated by a tool, please don't modify this file or  
//     you will lost all your modifications in the next regeneration.
//      The original t4 template to get this file is " ApplicationRemoteFacadeBaseSvcCsCT.tt" with "public class ApplicationRemoteFacadeBaseSvcCsCT : Template"
// 
//     .es Este código ha sido generado por una herramienta, por favor no modifique este fichero
//     o perdera las modificaciones al regenerar este fichero.
//      La plantilla con que se ha generado este fichero es "ApplicationRemoteFacadeBaseSvcCsCT.tt" con "public class ApplicationRemoteFacadeBaseSvcCsCT : Template"
//
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace Needel.Common.Application.WcfService
{
    #region sharedKernel usings
    #endregion 

    #region general usings
    using System;
    using System.Configuration;
    using System.Collections.Generic;
    using System.ServiceModel;

    using Inflexion2.Domain;
    //using Inflexion2.Application.Security.Data.Base;
    using Needel.Common.Application.Dtos;
    using Needel.Common.Domain;

    using Inflexion2.Application;
    //using Inflexion2.Application.DataTransfer.Core;
    //using Inflexion2.Application.Security.RemoteFacade;
    using Inflexion2.Infrastructure;

    using Needel.Common.Application;
    using Needel.Common.Application.WcfService.Contracts;
    //using AppSrvCore = Needel.Common.Application;
    #endregion

    /// <summary>
    /// Clase pública del servicio Wcf encargada de realizar las tareas 
    /// relacionadas con la entidad MNZ.
    /// </summary>
    [ApplicationErrorHandlerAttribute]
    public partial class MNZService : IMNZService
    {

        #region Fields

        /// <summary>
        /// Referencia a los servicios de administración de la entidad MNZ.
        /// </summary>
        private readonly Needel.Common.Application.IMNZServices service;

        #endregion

        #region CONSTRUCTORS

        /// <summary>
        /// Inicializa una nueva instancia de la clase <see cref="T:MNZService"/>.
        /// </summary>
        /// <remarks>
        /// Constructor de la clase <see cref="T:MNZService"/>.
        /// </remarks>
        public MNZService()
        {
            // HibernatingRhinos.Profiler.Appender.NHibernate.NHibernateProfiler.Initialize();
            // configuramos aqui el servicio o lo hacemos en el global asax
            // resolvemos con el ioc la interface de servicios de 
            this.service = new MNZServices();
        } // end MNZService Constructor

        #endregion

        #region Methods

        /// <summary>
        /// Función encargada de la creación de una entidad de tipo MNZ.
        /// </summary>
        /// <param name="mNZDto">
        /// Parámetro de tipo <see cref="MNZDto"/> con los datos necesarios
        /// para la creación de la entidad MNZ.
        /// </param>
        /// <return>
        /// Devuelve el dto del Objeto creado.
        /// </return>
        public MNZDto Create(MNZDto mNZDto)
        {
            // opción 1
            // Instanciamos el servicio de aplicación de creación mediante el contenedor de IoC.
            // var data = ManagerIoC.Container.Resolve<ICreateMNZ>();
            // Ejecutamos el servicio y obtenemos la respuesta.
            // Int32 identifier = data.Execute( mNZDto);
            // Devolvemos la respuesta.
            // return identifier;

            //opción 2
            MNZDto result = null;
            try
            {
                result = this.service.Create(mNZDto);
            }
            catch (Exception ex)
            {
                Inflexion2.Application.InternalException ie = new Inflexion2.Application.InternalException(ex);
                FaultObject.Throw<Inflexion2.Application.FaultObject>(ie);
            }

            return result;
        } // end Create

        /// <summary>
        /// Función encargada del borrado de una entidad de tipo MNZ.
        /// </summary>
        /// <param name="mNZDto">
        /// Parámetro que indica el identificador único de la entidad a borrar.
        /// </param>
        /// <returns>
        /// Devuelve <b>true</b> si la eliminación ha sido correcta y
        /// <b>false</b> en caso contrario.
        /// </returns>
        public bool Delete(MNZDto mNZDto)
        {
            // opción 1
            // Instanciamos el servicio de aplicación de borrado mediante el contenedor de IoC.
            // var data = ManagerIoC.Container.Resolve<IDeleteMNZ>();
            // Ejecutamos el servicio y obtenemos la respuesta.
            // bool response = data.Execute( mNZId);
            // Devolvemos la respuesta.
            //return response;

            //opcion 2
            bool result = false;
            try
            {
                result = this.service.Delete(mNZDto);
            }
            catch (Exception ex)
            {
                Inflexion2.Application.InternalException ie = new Inflexion2.Application.InternalException(ex);
                FaultObject.Throw<Inflexion2.Application.FaultObject>(ie);
            }

            return result;
        } // Delete

        /// <summary>
        /// Método encargado de obtener todas las entidades MNZ.
        /// </summary>
        /// <returns>
        /// Devuelve listado de Dto´s de la entidad MNZ.
        /// </returns>
        public IEnumerable<MNZDto> GetAll()
        {
            // opcion 1
            // Instanciamos el servicio de aplicación correspondiente mediante el contenedor de IoC.
            //var service = ManagerIoC.Container.Resolve<IGetAllMNZ>();
            // Ejecutamos el servicio y obtenemos la respuesta.
            //IEnumerable<MNZDto> result = service.Execute();
            // Devolvemos el resultado.
            //return result;
            
            // opcion 2
            IEnumerable<MNZDto> result = null;
            try
            {
                result = this.service.GetAll();
            }
            catch (Exception ex)
            {
                Inflexion2.Application.InternalException ie = new Inflexion2.Application.InternalException(ex);
                FaultObject.Throw<Inflexion2.Application.FaultObject>(ie);
            }

            return result;
        } // GetAll

        /// <summary>
        /// Recupera una lista paginada de entidades MNZ, según la especificación indicada.
        /// </summary>
        /// <param name="specificationDto">
        /// Especificación que se va a aplicar.
        /// </param>
        /// <returns>
        /// La lista paginada de entidades MNZ, según la especificación indicada.
        /// </returns>
        public PagedElements<MNZDto> GetPaged(SpecificationDto specificationDto)
        {
            PagedElements<MNZDto>	result = null;
            try
            {
                result = this.service.GetPaged(specificationDto);
            }
            catch (Exception ex)
            {
                Inflexion2.Application.InternalException ie = new Inflexion2.Application.InternalException(ex);
                FaultObject.Throw<Inflexion2.Application.FaultObject>(ie);
            }

            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public IEnumerable<MNZDto> DeleteAll()
        {
            IEnumerable<MNZDto> result = null;
            try
            {
                result = this.service.DeleteAll();
            }
            catch (Exception ex)
            {
                Inflexion2.Application.InternalException ie = new Inflexion2.Application.InternalException(ex);
                FaultObject.Throw<Inflexion2.Application.FaultObject>(ie);
            }

            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="mNZDto"></param>
        /// <returns></returns>
        public IEnumerable<MNZDto> GetAllExceptThis(MNZDto mNZDto)
        {
            IEnumerable<MNZDto> result = null;
            try
            {
                result = this.service.GetAllExceptThis(mNZDto);
            }
            catch (Exception ex)
            {
                Inflexion2.Application.InternalException ie = new Inflexion2.Application.InternalException(ex);
                FaultObject.Throw<Inflexion2.Application.FaultObject>(ie);
            }

            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="mNZDtos"></param>
        /// <returns></returns>
        public IEnumerable<MNZDto> GetAllExceptThese(IEnumerable<MNZDto> mNZDtos)
        {
            IEnumerable<MNZDto> result = null;
            try
            {
                result = this.service.GetAllExceptThese(mNZDtos);
            }
            catch (Exception ex)
            {
                Inflexion2.Application.InternalException ie = new Inflexion2.Application.InternalException(ex);
                FaultObject.Throw<Inflexion2.Application.FaultObject>(ie);
            }

            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="specificationDto"></param>
        /// <returns></returns>
        public IEnumerable<MNZDto> GetFiltered(SpecificationDto specificationDto)
        {
            IEnumerable<MNZDto> result = null;
            try
            {
                result = this.service.GetFiltered(specificationDto);
            }
            catch (Exception ex)
            {
                Inflexion2.Application.InternalException ie = new Inflexion2.Application.InternalException(ex);
                FaultObject.Throw<Inflexion2.Application.FaultObject>(ie);
            }

            return result;
        }

        #endregion

    } // end public partial class MNZService
} // end Needel.Common.Application.WcfService

