
#region Copyright info
//-----------------------------------------------------------------------
// <copyright file="GraphNode" company="Company">
//     Copyright (c) 2020. Company. All Rights Reserved.
//     Copyright (c) 2020. Company. Todos los derechos reservados.
//
//     .en This code has been generated by a tool, please don't modify this file or  
//     you will lost all your modifications in the next regeneration.
//      The original t4 template to get this file is " DomainBaseEntitySpecificationsCT.tt" with "public class DomainBaseEntitySpecificationsCT : Template"
// 
//     .es Este código ha sido generado por una herramienta, por favor no modifique este fichero
//     o perdera las modificaciones al regenerar este fichero.
//      La plantilla con que se ha generado este fichero es "DomainBaseEntitySpecificationsCT.tt" con "public class DomainBaseEntitySpecificationsCT : Template"
//
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace Needel.Common.Domain
{



    #region usings
    // en una clase parcial los using solo son necesarios una vez pero se dejan por si sirven de ayuda

    using System;
    using System.Linq;
    using Needel.Common.Domain;
    using Inflexion2.Domain;
    using Inflexion2;
    using Inflexion2.Domain.Specification;

    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    #endregion

    /// <summary>
    /// Clase que representa las especificaciones para la entidad <see cref="T:GraphNode"/>.
    /// </summary>
    /// <remarks>
    /// Sin comentarios adicionales.
    /// </remarks>
    public static class GraphNodeSpecifications
    {
        #region GraphNode Basic Specifications

        // ha continuación se incorporan las especificaciones correspondientes a los campos marcados como filter o como identification
 
        /// <summary>
        /// Método que devuelve especificación de aquellos objetos de tipo GraphNode  
        /// seleccionados por el valor del campo Name.
        /// </summary>
        /// <param name="name">
        /// Parámetro que indica el valor del campo Name.
        /// </param>
        /// <returns>
        /// Devuelve <see cref="Specification{GraphNode}"/> asociado con este criterio.
        /// </returns>
        public static Specification<GraphNode> FindAllByName(string name)
        {
            // Especificación para GraphNode por Name
            Specification<GraphNode> specification =
                            new DirectSpecification<GraphNode>(c => c.Name == name);
            // Devolvemos la especificación.
            return specification;
        } // FindAllByName


        
        #endregion

        #region GraphNode Complex Specifications
        #endregion

    } // class GraphNode

} //  Needel.Common.Domain

